import {
  Bell,
  BellRinging,
  Broadcast,
  ChartLine,
  ClockCounterClockwise,
  Export,
  Eye,
  FileText,
  Flask,
  Gavel,
  GitCommit,
  HardDrives,
  House,
  ListBullets,
  Notepad,
  Path,
  PencilSimple,
  Plug,
  Plugs,
  Plus,
  Pulse,
  Receipt,
  Robot,
  Scroll,
  SealCheck,
  SquaresFour,
  Stack,
  Tray,
  UserCircle,
  Users,
  type Icon as IconType,
} from "@phosphor-icons/react";
import type { AgentSectionKey } from "@/lib/screens";

/** One icon per screen, shared by the dock, the phone tabs and More. */
export const SCREEN_ICON: Record<string, IconType> = {
  home: House,
  approvals: Tray,
  alerts: Bell,
  agents: Robot,
  positions: Stack,
  "agents-new": Plus,
  connections: Plugs,
  "audit-trace": Path,
  "audit-decisions": Gavel,
  "audit-timeline": ClockCounterClockwise,
  "audit-surveillance": Eye,
  "audit-export": Export,
  "audit-verify": SealCheck,
  "settings-policies": Scroll,
  "settings-members": Users,
  "settings-notifications": BellRinging,
  "settings-clients": Plug,
  "settings-disclosures": FileText,
  "settings-billing": Receipt,
  "settings-deployment": HardDrives,
  "settings-profile": UserCircle,
};

export const SECTION_ICON: Record<AgentSectionKey, IconType> = {
  overview: SquaresFour,
  positions: Stack,
  orders: ListBullets,
  decisions: Gavel,
  approvals: Tray,
  mandate: Scroll,
  "mandate/versions": GitCommit,
  "mandate/edit": PencilSimple,
  prove: Flask,
  "prove/backtests": ChartLine,
  "prove/paper": Notepad,
  "prove/live": Broadcast,
  activity: Pulse,
};
