//! One [`Permission`] per row of identity spec §4.2, the closed set other lanes route on.

/// One variant per row of identity spec §4.2, in its order.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[allow(missing_docs, reason = "each variant is the §4.2 row of the same name")]
pub enum Permission {
    ViewAgents,
    OwnerRequest,
    DryRun,
    ChatThread,
    ReadRecords,
    DraftVersion,
    ConfirmReducingOrNeutral,
    ConfirmRiskIncreasing,
    Deploy,
    Pause,
    HoldNewOpenings,
    LiftClientHold,
    ResumeOrStop,
    KillSwitchAgent,
    KillSwitchConnectionOrWorkspace,
    KillSwitchOrg,
    KillSwitchPrivileges,
    ReenableHaltedScope,
    OwnerExit,
    Acknowledge,
    Approve,
    Skip,
    RemoveOrNarrowDelegation,
    BrokerConnection,
    AcceptDisclosure,
    WorkspacePolicyTighten,
    WorkspacePolicyLoosen,
    WorkspaceMembers,
    WorkspaceRoles,
    ConnectClient,
    RevokeClient,
    OwnPasskey,
    NotificationAddress,
    ListOwnNotificationAddresses,
    ListOwnMemberships,
    Leave,
    OrgPolicyTighten,
    OrgPolicyLoosen,
    SsoConfiguration,
    CreateOrArchiveWorkspace,
    OrgMemberships,
    ServiceAccounts,
    Billing,
    TransferOrDeleteOrg,
    ApproveBreakGlass,
    BreakGlassOperational,
}
