"""Generates the agent-stream vectors of docs/specs/reference-cases/journal.yaml (DEC-177).

Journal spec §9.1 closes the agent stream's payload schemas; this script is their reference
implementation. It:

1. canonicalizes per spec §4 and proves it by reproducing every version-3 vector (chain bodies and
   hashes, the export line, string escaping, and decimal normalization) before trusting itself;
2. builds the artifacts and the agent-stream chain, hashing each body onto the previous one;
3. validates every draft against the closed schemas and the §9.1 consistency and subject rules:
   each chain event must pass every rule, and each invalid draft must break exactly the one rule
   it names, with the reason and path it expects;
4. recomputes the `DecisionMade` numbers from the model output and weights (mandate spec §8.3) by
   an independent path, and checks `IntentProposed` against the account chain's `IntentReceived`;
5. seeds bugs, into the validator and into the vectors, and requires every one to be caught.

Usage: `generate.py` (or `generate.py --write`) rewrites the agent-stream section of journal.yaml;
`generate.py --check` fails if the file differs from what this script generates.
"""

import argparse
import calendar
import copy
import functools
import hashlib
import itertools
import math
import re
import sys
from dataclasses import dataclass
from datetime import datetime
from decimal import ROUND_CEILING, ROUND_DOWN, ROUND_HALF_EVEN, Decimal, InvalidOperation, localcontext
from fractions import Fraction
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
VECTORS = ROOT / "docs/specs/reference-cases/journal.yaml"
TRADING_CASES = ROOT / "docs/specs/reference-cases/trading-domain.yaml"
MARKER = "# ==== agent_stream: generated by reference/journal/generate.py (DEC-177); do not edit by hand ===="

# --------------------------------------------------------------------------- spec §4: canonical form

KEY = re.compile(r"^[a-z][a-z0-9_]{0,63}$")
SHORT_ESCAPES = {'"': '\\"', "\\": "\\\\", "\b": "\\b", "\f": "\\f", "\n": "\\n", "\r": "\\r", "\t": "\\t"}
MAX_INT = 2**53 - 1


def canon_str(text: str) -> str:
    out = []
    for ch in text:
        code = ord(ch)
        if ch in SHORT_ESCAPES:
            out.append(SHORT_ESCAPES[ch])
        elif code < 0x20:
            out.append(f"\\u{code:04x}")
        elif 0xD800 <= code <= 0xDFFF:
            raise ValueError("lone surrogate (spec §4.3)")
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'


def canon(value) -> str:
    """The canonical JSON text of a value tree (spec §4); bytes are its UTF-8 encoding."""
    match value:
        case None:
            return "null"
        case bool():
            return "true" if value else "false"
        case int():
            if not 0 <= value <= MAX_INT:
                raise ValueError(f"integer out of range: {value}")
            return str(value)
        case float():
            raise ValueError("floating-point numbers are rejected (spec §4.5)")
        case str():
            return canon_str(value)
        case list():
            return "[" + ",".join(canon(item) for item in value) + "]"
        case dict():
            for key in value:
                if not KEY.match(key):
                    raise ValueError(f"key outside the spec §4.1 charset: {key!r}")
            return "{" + ",".join(f"{canon_str(k)}:{canon(value[k])}" for k in sorted(value)) + "}"
    raise TypeError(f"not a JSON value: {value!r}")


def canon_bytes(value) -> bytes:
    return canon(value).encode("utf-8")


def sha256_hex(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


DECIMAL_INPUT = re.compile(r"^-?(\d+\.?\d*|\.\d+)([eE][+-]?\d+)?$")
DECIMAL_CANONICAL = re.compile(r"^-?(0|[1-9][0-9]*)(\.[0-9]*[1-9])?$")
DECIMAL_BOUND = Decimal("7.9e28")


def normalize_decimal(text: str) -> str | None:
    """The canonical form of a decimal input, or None if spec §4.6 rejects it."""
    if not DECIMAL_INPUT.match(text):
        return None
    try:
        number = Decimal(text)
    except InvalidOperation:
        return None
    if abs(number) >= DECIMAL_BOUND:
        return None
    plain = format(number, "f")
    if "." in plain:
        plain = plain.rstrip("0").rstrip(".")
    if plain in ("-0", ""):
        plain = "0"
    fraction = plain.partition(".")[2]
    if len(fraction) > 28:
        return None
    return plain


TIMESTAMP = re.compile(r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{9}Z$")


def is_timestamp(text: str) -> bool:
    if not TIMESTAMP.match(text):
        return False
    try:
        instant = datetime.strptime(text[:19], "%Y-%m-%dT%H:%M:%S")
    except ValueError:
        return False
    return 1970 <= instant.year <= 9999


def parse_instant(text: str) -> tuple[datetime, int]:
    return datetime.strptime(text[:19], "%Y-%m-%dT%H:%M:%S"), int(text[20:29])


def epoch_seconds(text: str) -> int:
    """The runtime's risk-clock form of an instant, which the invalid drafts show being refused."""
    return calendar.timegm(parse_instant(text)[0].timetuple())


IDENT = re.compile(r"^[A-Za-z0-9_-]+$")
ULID_ALPHABET = set("0123456789ABCDEFGHJKMNPQRSTVWXYZ")
DIGEST = re.compile(r"^sha256:[0-9a-f]{64}$")


def is_ulid(text: str) -> bool:
    return len(text) == 26 and set(text) <= ULID_ALPHABET and text[0] <= "7"


# --------------------------------------------------------------------------- self-test on version 3


def self_test(v3: dict) -> None:
    """The canonicalizer reproduces every version-3 vector before anything it produces is trusted."""
    for entry in v3["chain"]:
        text = canon(entry["body"])
        assert text == entry["canonical"], f"v3 seq {entry['seq']}: canonical differs"
        assert sha256_hex(text.encode()) == entry["hash"], f"v3 seq {entry['seq']}: hash differs"
    first = v3["chain"][0]
    assert canon({"body": first["body"], "hash": first["hash"]}) == v3["export_line_seq_1"]
    escaping = v3["string_escaping"]
    data = canon_bytes(escaping["object"])
    assert data.hex() == escaping["canonical_utf8_hex"], "v3 string escaping differs"
    assert sha256_hex(data) == escaping["hash"]
    for case in v3["decimal_normalization"]["accept"]:
        assert normalize_decimal(str(case["input"])) == case["canonical"], case
    for rejected in v3["decimal_normalization"]["reject"]:
        assert normalize_decimal(str(rejected)) is None, rejected


# --------------------------------------------------------------------------- closed schemas (§9.1)


@dataclass(frozen=True)
class T:
    """One field type, mirroring the journal's payload type system."""

    kind: str
    inner: T | None = None
    options: tuple[str, ...] = ()
    fields: tuple[tuple[str, T], ...] = ()


STR, ID, ULID, DEC, INT, BOOL, TS, REF = (
    T(k) for k in ("str", "id", "ulid", "dec", "int", "bool", "ts", "ref")
)


def one_of(*options: str) -> T:
    return T("one_of", options=options)


def opt(inner: T) -> T:
    return T("nullable", inner=inner)


def list_of(inner: T) -> T:
    return T("list", inner=inner)


def rec(*fields: tuple[str, T]) -> T:
    return T("record", fields=fields)


MODES = ("normal", "exits_only", "paused", "stopped")
MODE = one_of(*MODES)
LIFECYCLE = one_of("normal", "paused", "stopped")
MODE_REASONS = one_of(
    "restriction_changed",
    "awaiting_reconciliation",
    "owner_pause",
    "owner_resume",
    "owner_stop",
    "kill_switch",
)
SIDE = one_of("buy", "sell")
ORDER_TYPE = one_of("limit", "market")
TIF = one_of("day", "gtc", "ioc")
RISK_ADDING = ("open", "increase")
DECISION_PURPOSE = one_of("open", "increase", "discretionary_exit", "risk_exit")
INTENT_PURPOSE = one_of("open", "increase", "discretionary_exit", "risk_exit", "owner_exit")
CLIPS = (
    "max_order_usd",
    "position_cap",
    "gross_exposure_cap",
    "target_qty",
    "max_spend_usd",
    "max_avg_price",
)
IGNORED = one_of(
    "not_pinned",
    "model_withdrawn",
    "output_limits",
    "not_in_universe",
    "direction_not_allowed",
    "horizon_mismatch",
    "revision_without_predecessor",
)
EXIT_ORIGIN = one_of("signal", "goal_completion", "removed_instrument")
ASK_SUPPRESSED = one_of("budget", "skipped_today", "recent_timeout")
STEP_UP = rec(("assertion_id", STR), ("authenticated_at", TS), ("method", STR))

SCHEMAS: dict[tuple[str, str], T] = {
    ("agent", "StreamOpened"): rec(("stream_type", one_of("agent")), ("workspace_id", ID), ("agent_id", ID)),
    ("agent", "ObservationRecorded"): rec(
        ("source", STR), ("instrument_id", opt(STR)), ("as_of", TS), ("data_ref", REF)
    ),
    ("agent", "ModelOutputRecorded"): rec(
        ("model_id", STR),
        ("model_version", STR),
        ("content_hash", REF),
        ("instrument_id", STR),
        ("as_of", TS),
        ("expires_at", TS),
        ("direction", STR),
        ("conviction", DEC),
        ("confidence", DEC),
        ("horizon_s", INT),
        ("thesis_ref", opt(REF)),
        ("evidence", list_of(ULID)),
        ("invalidation", opt(STR)),
        ("thesis_id", opt(ID)),
        ("lineage_id", opt(ID)),
        ("ignored", opt(IGNORED)),
    ),
    ("agent", "DecisionMade"): rec(
        ("instrument_id", STR),
        ("side", SIDE),
        ("type", ORDER_TYPE),
        ("tif", TIF),
        ("qty", DEC),
        ("limit_price", opt(DEC)),
        ("purpose", DECISION_PURPOSE),
        ("exit_origin", opt(EXIT_ORIGIN)),
        ("exit_conviction", opt(DEC)),
        ("buy_conviction", opt(DEC)),
        ("combined_score", opt(DEC)),
        ("outputs_used", list_of(ULID)),
        ("model_weights", list_of(rec(("key", STR), ("value", DEC)))),
        ("clips_applied", list_of(one_of(*CLIPS))),
        ("dry_run", one_of("allow", "deny", "defer")),
        ("reason_code", opt(ID)),
        ("autonomy", opt(one_of("auto", "ask", "deny"))),
        ("ask_suppressed", opt(ASK_SUPPRESSED)),
    ),
    ("agent", "IntentProposed"): rec(
        ("instrument_id", STR),
        ("side", SIDE),
        ("type", ORDER_TYPE),
        ("tif", TIF),
        ("qty", DEC),
        ("limit_price", opt(DEC)),
        ("purpose", INTENT_PURPOSE),
    ),
    ("agent", "AgentModeChanged"): rec(
        ("from", MODE), ("to", MODE), ("reason", MODE_REASONS), ("lifecycle", LIFECYCLE)
    ),
    ("agent", "KillSwitchActivated"): rec(
        ("scope", one_of("agent", "connection", "workspace")),
        ("subject", ID),
        ("initiator", one_of("owner", "risk_limit", "platform_operator")),
        ("mode_event", opt(ULID)),
    ),
    ("agent", "OwnerExitRequested"): rec(
        ("scope", one_of("instrument", "agent", "connection", "workspace")),
        ("subject", ID),
        ("confirmed", BOOL),
        ("bid", opt(DEC)),
        ("bid_size", opt(DEC)),
        ("floor", opt(DEC)),
        ("user", STR),
        ("step_up_status", one_of("valid", "absent", "stale")),
        ("step_up", opt(STEP_UP)),
    ),
}

REQUIRED_REFS = {
    "StreamOpened": (),
    "ObservationRecorded": (),
    "ModelOutputRecorded": ("mandate_version",),
    "DecisionMade": ("mandate_version",),
    "IntentProposed": ("mandate_version",),
    "AgentModeChanged": (),
    "KillSwitchActivated": (),
    "OwnerExitRequested": ("mandate_version",),
}
CONFIG_REF_KINDS = (
    "fee_config",
    "trading_calendar",
    "settlement_calendar",
    "instrument_snapshot",
    "rule_set",
    "mandate_version",
    "model_version",
)
ENVELOPE = rec(
    ("envelope_version", INT),
    ("environment", one_of("paper", "live", "backtest")),
    ("event_id", ULID),
    ("stream_id", STR),
    ("event_type", STR),
    ("schema_version", INT),
    ("event_time", TS),
    ("clock_source", one_of("broker", "exchange", "local", "scheduler")),
    ("causation_id", opt(ULID)),
    ("correlation_id", opt(ULID)),
    (
        "actor",
        rec(
            ("kind", one_of("system", "agent", "user", "broker", "platform_operator")),
            ("id", STR),
            ("version", STR),
            ("build", opt(REF)),
        ),
    ),
    ("config_refs", T("object")),
    ("payload", T("object")),
    ("artifact_refs", list_of(REF)),
    ("pii_refs", list_of(STR)),
)
JOURNAL_FIELDS = ("seq", "prev_hash", "recorded_at")

REGRESSIONS = {
    "regress.lifecycle_as_mode": (("agent", "AgentModeChanged"), "lifecycle", MODE),
}


def schema_for(event_type: str, skip: frozenset[str]) -> T:
    """The closed schema, or for a regression mutant the reviewed head's wider one."""
    schema = SCHEMAS[("agent", event_type)]
    for name, (key, member, wider) in REGRESSIONS.items():
        if name in skip and key == ("agent", event_type):
            schema = rec(*((m, wider if m == member else t) for m, t in schema.fields))
    return schema


@dataclass(frozen=True)
class Violation:
    rule: str
    reason: str
    path: str


def type_violations(ty: T, value, path: str, skip: frozenset[str]) -> list[Violation]:
    """Every type violation, in the order the journal reports them: extra members first (in key
    order), then the declared members in declaration order."""

    def bad(reason: str, rule: str = "types") -> list[Violation]:
        return [Violation(rule, reason, path)]

    kind = ty.kind
    if kind == "nullable":
        return [] if value is None else type_violations(ty.inner, value, path, skip)
    if kind == "record":
        if not isinstance(value, dict):
            return bad("schema")
        names = [name for name, _ in ty.fields]
        out = []
        if "record.extra" not in skip:
            out += [
                Violation("record.extra", "schema", f"{path}.{k}".lstrip("."))
                for k in sorted(value)
                if k not in names
            ]
        for name, inner in ty.fields:
            member = f"{path}.{name}".lstrip(".")
            if name not in value:
                if "record.missing" not in skip:
                    out.append(Violation("record.missing", "schema", member))
            else:
                out += type_violations(inner, value[name], member, skip)
        return out
    if kind == "list":
        if not isinstance(value, list):
            return bad("schema")
        return [
            v for i, item in enumerate(value) for v in type_violations(ty.inner, item, f"{path}[{i}]", skip)
        ]
    if kind == "object":
        return [] if isinstance(value, dict) else bad("schema")
    if kind == "int":
        ok = isinstance(value, int) and not isinstance(value, bool) and 0 <= value <= MAX_INT
        return [] if ok else bad("schema")
    if kind == "bool":
        return [] if isinstance(value, bool) else bad("schema")
    if not isinstance(value, str):
        return bad("schema")
    checks = {
        "str": lambda s: s != "" or "types.str_nonempty" in skip,
        "id": lambda s: bool(IDENT.match(s)),
        "ulid": is_ulid,
        "dec": lambda s: normalize_decimal(s) is not None,
        "ts": lambda s: is_timestamp(s) or "types.timestamp" in skip,
        "ref": lambda s: bool(DIGEST.match(s)),
        "one_of": lambda s: s in ty.options,
    }
    return [] if checks[kind](value) else bad("non_canonical")


def digest_strings(value) -> set[str]:
    match value:
        case str() if DIGEST.match(value):
            return {value}
        case list():
            return set().union(*(digest_strings(v) for v in value)) if value else set()
        case dict():
            return set().union(*(digest_strings(v) for v in value.values())) if value else set()
    return set()


def ascending(items: list) -> bool:
    """Strictly ascending, so a repeat is refused as well as a swap."""
    return all(a < b for a, b in itertools.pairwise(items))


def strictness(mode: str) -> int:
    return MODES.index(mode)


def consistency_violations(event_type: str, draft: dict, skip: frozenset[str]) -> list[Violation]:
    """The §9.1 consistency rules, evaluated only on a well-typed payload, each reported once."""
    p = draft["payload"]
    out: list[Violation] = []

    def rule(number: int | str, holds: bool, reason: str, path: str) -> None:
        name = f"rule.{number}"
        if not holds and name not in skip:
            out.append(Violation(name, reason, path))

    if event_type in ("DecisionMade", "IntentProposed"):
        adds_risk = p["purpose"] in RISK_ADDING
        rule(1, (p["side"] == "buy") == adds_risk, "schema", "payload.side")
        priced = p["limit_price"] is not None
        rule(2, priced == (p["type"] == "limit"), "schema", "payload.limit_price")
        rule(3, p["type"] != "market" or not adds_risk, "schema", "payload.type")
    if event_type == "DecisionMade":
        allow = p["dry_run"] == "allow"
        rule(4, (p["reason_code"] is None) == allow, "schema", "payload.reason_code")
        rule(5, (p["autonomy"] is not None) == allow, "schema", "payload.autonomy")
        rule(6, p["dry_run"] != "defer" or p["purpose"] == "discretionary_exit", "schema", "payload.dry_run")
        rule(7, p["autonomy"] in (None, "auto") or p["purpose"] in RISK_ADDING, "schema", "payload.autonomy")
        asked = p["autonomy"] == "ask"
        rule("7.ask_suppressed", p["ask_suppressed"] is None or asked, "schema", "payload.ask_suppressed")
        discretionary = p["purpose"] == "discretionary_exit"
        rule("8.exit_origin", (p["exit_origin"] is not None) == discretionary, "schema", "payload.exit_origin")
        evaluated = adds_risk or p["exit_origin"] == "signal"
        if "regress.rule_8_numbers_on_every_exit_but_risk" in skip:
            evaluated = p["purpose"] != "risk_exit"
        wrong = [
            m for m in ("exit_conviction", "buy_conviction", "combined_score") if (p[m] is not None) != evaluated
        ]
        if not evaluated and "regress.rule_8_numbers_on_every_exit_but_risk" not in skip:
            wrong += [m for m in ("outputs_used", "model_weights", "clips_applied") if p[m]]
        rule(8, not wrong, "schema", f"payload.{wrong[0]}" if wrong else "")
        rule(9, ascending(p["outputs_used"]), "non_canonical", "payload.outputs_used")
        keys = [w["key"].encode() for w in p["model_weights"]]
        rule(9, ascending(keys), "non_canonical", "payload.model_weights")
        order = [CLIPS.index(c) for c in p["clips_applied"]]
        rule(9, ascending(order), "non_canonical", "payload.clips_applied")
    if event_type == "IntentProposed":
        rule(10, draft["causation_id"] is not None, "schema", "causation_id")
    if event_type == "AgentModeChanged":
        at_least = strictness(p["to"]) >= strictness(p["lifecycle"])
        if "boundary.rule_11_strictly_stricter" in skip:
            at_least = strictness(p["to"]) > strictness(p["lifecycle"])
        rule(11, at_least, "schema", "payload.to")
    if event_type == "OwnerExitRequested":
        members = ("bid", "bid_size", "floor")
        if "regress.rule_12_ties_evidence_to_the_bid" in skip:
            members = (*members, "user", "step_up")
        wrong = [m for m in members if (p[m] is not None) != p["confirmed"]]
        rule(12, not wrong, "schema", f"payload.{wrong[0]}" if wrong else "")
        valid = p["step_up_status"] == "valid"
        rule("12.step_up", (p["step_up"] is not None) == valid, "schema", "payload.step_up")
    if event_type == "ModelOutputRecorded" and (p["thesis_id"] is None) != (p["lineage_id"] is None):
        rule(13, False, "schema", "payload.thesis_id" if p["thesis_id"] is None else "payload.lineage_id")
    return out


def subject_violations(event_type: str, draft: dict, skip: frozenset[str]) -> list[Violation]:
    """Rules 14 and 15: a payload that names a subject names this stream's (reason `stream_mismatch`)."""
    _, workspace, agent = draft["stream_id"].split(":")
    p = draft["payload"]
    out = []
    opened = f"agent:{p.get('workspace_id')}:{p.get('agent_id')}"
    if event_type == "StreamOpened" and "rule.14" not in skip and opened != draft["stream_id"]:
        out.append(Violation("rule.14", "stream_mismatch", "stream_id"))
    if event_type in ("KillSwitchActivated", "OwnerExitRequested"):
        expected = {"agent": agent, "workspace": workspace}.get(p["scope"])
        if expected is not None and p["subject"] != expected and f"rule.15.{p['scope']}" not in skip:
            out.append(Violation(f"rule.15.{p['scope']}", "stream_mismatch", "payload.subject"))
    return out


def violations(draft: dict, skip: frozenset[str] = frozenset()) -> list[Violation]:
    """Every rule an agent-stream draft breaks, in the journal's check order (spec §9.1)."""
    out = type_violations(ENVELOPE, draft, "", skip)
    if out:
        return out
    if draft["envelope_version"] != 1:
        return [Violation("envelope", "schema", "envelope_version")]
    event_type = draft["event_type"]
    stream = draft["stream_id"].split(":")
    if event_type not in REQUIRED_REFS:
        return [Violation("catalogue", "unknown_event_type", "event_type")]
    if len(stream) != 3 or not all(IDENT.match(s) for s in stream):
        return [Violation("stream", "non_canonical", "stream_id")]
    if stream[0] != "agent":
        return [Violation("stream", "wrong_stream", "event_type")]
    if draft["actor"]["kind"] in ("system", "agent") and draft["actor"]["build"] is None:
        out.append(Violation("actor", "schema", "actor.build"))
    refs = draft["config_refs"]
    for kind in sorted(refs):
        if kind not in CONFIG_REF_KINDS:
            out.append(Violation("config_refs", "schema", f"config_refs.{kind}"))
        elif not (isinstance(refs[kind], str) and DIGEST.match(refs[kind])):
            out.append(Violation("config_refs", "non_canonical", f"config_refs.{kind}"))
    if "config_refs.required" not in skip:
        missing = [k for k in REQUIRED_REFS[event_type] if k not in refs]
        out += [
            Violation("config_refs.required", "missing_config_ref", f"config_refs.{k}") for k in missing[:1]
        ]
    if draft["schema_version"] != 1:
        return [*out, Violation("catalogue", "unknown_schema", "payload")]
    schema = schema_for(event_type, skip)
    payload_types = type_violations(schema, draft["payload"], "payload", skip)
    out += payload_types
    as_read = {**draft, "payload": {name: draft["payload"].get(name) for name, _ in schema.fields}}
    if not payload_types:
        out += consistency_violations(event_type, as_read, skip)
    if "artifact_refs" not in skip and draft["artifact_refs"] != sorted(digest_strings(draft["payload"])):
        out.append(Violation("artifact_refs", "artifact_refs", "artifact_refs"))
    if not ascending(draft["pii_refs"]):
        out.append(Violation("pii_refs", "pii_refs", "pii_refs"))
    if not payload_types:
        out += subject_violations(event_type, as_read, skip)
    return out


ACTION = ("instrument_id", "side", "type", "tif", "qty", "limit_price", "purpose")
DECIMAL_ACTION = ("qty", "limit_price")


def action_of(payload: dict) -> dict:
    """`IntentProposed`'s members as values: decimals compared by their normalized form (§4.6)."""
    return {
        m: normalize_decimal(payload[m]) if m in DECIMAL_ACTION and payload[m] is not None else payload[m]
        for m in ACTION
    }


def batch_violations(drafts: list[dict], skip: frozenset[str] = frozenset()) -> list[tuple[int, Violation]]:
    """An `append` batch (§5.1), refused whole on any violation: each draft's own, in draft order,
    then rule 10's second clause, on an `IntentProposed` whose `DecisionMade` is in the batch."""
    out = [(i, v) for i, draft in enumerate(drafts) for v in violations(draft, skip)]
    if out or "rule.10.batch" in skip:
        return out
    decisions = {d["event_id"]: d for d in drafts if d["event_type"] == "DecisionMade"}
    for i, draft in enumerate(drafts):
        cause = decisions.get(draft["causation_id"]) if draft["event_type"] == "IntentProposed" else None
        if cause is None:
            continue
        mine, theirs = action_of(draft["payload"]), action_of(cause["payload"])
        differs = [m for m in ACTION if mine[m] != theirs[m]]
        if differs:
            out.append((i, Violation("rule.10.batch", "schema", f"payload.{differs[0]}")))
    return out


def verify_range(entries: list[dict], from_seq: int, skip: frozenset[str] = frozenset()) -> list[tuple[int, str]]:
    """§11's per-range checks that span agent-stream events, over a range whose earlier events are
    not in hand: a reference to an event before `from_seq` is not checked."""
    seen: dict[str, dict] = {}
    out = []
    for entry in entries:
        body = entry["body"]
        p = body["payload"]
        if body["event_type"] == "IntentProposed" and "verify.intent_action_mismatch" not in skip:
            cause = seen.get(body["causation_id"])
            if cause is not None and cause["event_type"] == "DecisionMade" and action_of(cause["payload"]) != action_of(p):
                out.append((body["seq"], "intent_action_mismatch"))
        if body["event_type"] == "KillSwitchActivated" and p["mode_event"] is not None:
            named = seen.get(p["mode_event"])
            is_mode = named is not None and named["event_type"] == "AgentModeChanged"
            clauses = {
                "verify.mode_event_mismatch.unresolved": named is None and from_seq == 1,
                "verify.mode_event_mismatch.event_type": named is not None and not is_mode,
                "verify.mode_event_mismatch.reason": is_mode and named["payload"]["reason"] != "kill_switch",
            }
            if any(broken and clause not in skip for clause, broken in clauses.items()):
                out.append((body["seq"], "mode_event_mismatch"))
        seen[body["event_id"]] = body
    return out


# --------------------------------------------------------------------------- the agent stream

WORKSPACE = "ws_01J8Z2"
AGENT = "agent_a"
STREAM = f"agent:{WORKSPACE}:{AGENT}"
INSTRUMENT = "b0b6dd9d-8b9b-48a9-ba46-b9d54906e415"
HELD_INSTRUMENT = "5f0c2a4e-7d1b-4c3e-9a8f-2b6d1e0c4a7f"
MANDATE = {"mandate_version": "sha256:" + "5" * 64}
ACTOR = {"kind": "agent", "id": AGENT, "version": "0.1.0", "build": "sha256:" + "c" * 64}
INTENT_ID = "01J8Z3M1P0000000000000000X"
CHAIN = (
    ("opened", "01J8Z3JYA000000000000000G1"),
    ("observation", "01J8Z3M0A000000000000000G2"),
    ("model_output", "01J8Z3M0R000000000000000G3"),
    ("decision", "01J8Z3M1A000000000000000G4"),
    ("intent", INTENT_ID),
    ("owner_close_in_session", "01J8Z6A0A000000000000000E1"),
    ("owner_close_in_session_intent", "01J8Z6A0M000000000000000P1"),
    ("goal_exit", "01J8ZMA0A000000000000000D2"),
    ("owner_close_confirmed", "01J8ZMR0A000000000000000E2"),
    ("owner_close_confirmed_intent", "01J8ZMR0M000000000000000P2"),
    ("kill_switch_mode", "01J8ZNB0A000000000000000M1"),
    ("owner_kill_switch", "01J8ZNB0M000000000000000K1"),
    ("kill_switch", "01J8ZNB0R000000000000000K2"),
)
SEQ = {name: seq for seq, (name, _) in enumerate(CHAIN, start=1)}
ID = dict(CHAIN)
ABSENT_EVENT_ID = "01J8ZNB0A000000000000000Z9"
assert is_ulid(ABSENT_EVENT_ID) and ABSENT_EVENT_ID not in ID.values(), "names no event of the chain"

QUOTE_SNAPSHOT = {
    "kind": "quote_snapshot",
    "instrument_id": INSTRUMENT,
    "feed": "iex",
    "as_of": "2026-09-21T13:59:58.000000000Z",
    "bid": "149.98",
    "bid_size": "300",
    "ask": "150",
    "ask_size": "200",
}
MODEL_CONTENT = {
    "kind": "signal_model",
    "model_id": "quant.mean_reversion",
    "model_version": "1.0.0",
    "authorship": "platform",
    "code": "reference fixture: stands for the model code, prompt, and parameter schema (mandate spec §8.1)",
    "parameter_schema": {"lookback_days": "integer"},
}
ARTIFACTS = {"quote_snapshot": QUOTE_SNAPSHOT, "model_content": MODEL_CONTENT}

DERIVATION = {
    "note": (
        "Illustrative mandate and account values the DecisionMade vector is recomputed from "
        "(mandate spec §8.3); not a mandate reference case. quant.momentum is configured but has no "
        "fresh output, so it counts as missing. The ask is the observed quote's (artifact quote_snapshot). "
        "The gate dry run and the autonomy result are inputs. Gross exposure is the held position's "
        "quantity x mark. After the session closes the profit_stop goal is reached, whose completion "
        "is a discretionary exit of every position (mandate spec §3.1), deferred until the session "
        "(trading spec §9.6) with nothing proposed (mandate spec §6.2). Outside the session an exit is a "
        "limit order (trading spec §9.4), priced at the exit price ladder's first rung: the reference bid "
        "x (1 - exit_offset) for the >= 50 M USD tier, a sell rounded up to the tick (trading spec §2.1, "
        "§5.6). The owner closes the held position in the regular session without a "
        "confirmed bid, and after the session closes the opened position (taken as filled) with a "
        "confirmed bid, whose floor is the default, bid x (1 - max_exit_offset), for the instrument's "
        ">= 50 M USD tier (trading spec §5.5, §5.6); that close's own limit is the floor. Step-up is "
        "valid for 300 s after authentication (DEC-156 item 8). The regular session is 09:30 to 16:00 "
        "America/New_York (EDT, UTC-4, on this date)."
    ),
    "owner_bid": "151",
    "goal_exit_reference_bid": "151",
    "exit_offset": "0.005",
    "equity_tick": "0.01",
    "max_exit_offset": "0.03",
    "step_up_max_age_s": 300,
    "goal": "profit_stop",
    "regular_session_utc": {"open": "2026-09-21T13:30:00.000000000Z", "close": "2026-09-21T20:00:00.000000000Z"},
    "held": {"instrument_id": HELD_INSTRUMENT, "qty": "5", "mark": "100"},
    "now": "2026-09-21T14:00:00.000000000Z",
    "models": [
        {"model_id": "quant.mean_reversion", "weight": "0.9", "max_output_age_s": 300},
        {"model_id": "quant.momentum", "weight": "0.1", "max_output_age_s": 300},
    ],
    "equity": "10000",
    "market_value": "0",
    "working_opening_cost": "0",
    "max_position_usd": "5000",
    "max_position_fraction": "0.2",
    "size_factor": "1",
    "entry_threshold": "0.3",
    "exit_threshold": "0.3",
    "rebalance_band": "0.05",
    "max_order_usd": "1500",
    "max_gross_exposure_usd": "10000",
    "increment": "1",
    "min_order_qty": "1",
    "tif": "day",
    "dry_run": "allow",
    "autonomy": "auto",
}


def default_floor(d: dict) -> str:
    return normalize_decimal(str(Decimal(d["owner_bid"]) * (1 - Decimal(d["max_exit_offset"]))))


def first_rung_sell_limit(d: dict) -> str:
    """Trading spec §5.6 step 1 for a sell, rounded up to the tick as §2.1 rounds a sell limit."""
    raw = Decimal(d["goal_exit_reference_bid"]) * (1 - Decimal(d["exit_offset"]))
    return normalize_decimal(str(raw.quantize(Decimal(d["equity_tick"]), rounding=ROUND_CEILING)))


def artifact_ref(obj: dict) -> str:
    return "sha256:" + sha256_hex(canon_bytes(obj))


def event(name: str, event_type: str, at: str, recorded: str, payload: dict, **envelope) -> dict:
    body = {
        "envelope_version": 1,
        "environment": "paper",
        "event_id": ID[name],
        "stream_id": STREAM,
        "seq": SEQ[name],
        "event_type": event_type,
        "schema_version": 1,
        "event_time": at,
        "recorded_at": recorded,
        "clock_source": envelope.get("clock_source", "scheduler"),
        "causation_id": envelope.get("causation_id"),
        "correlation_id": None,
        "actor": dict(ACTOR),
        "config_refs": dict(MANDATE) if REQUIRED_REFS[event_type] else {},
        "payload": payload,
        "artifact_refs": sorted(digest_strings(payload)),
        "pii_refs": [],
        "prev_hash": None,
    }
    return body


def chain_bodies() -> list[dict]:
    quote_ref = artifact_ref(QUOTE_SNAPSHOT)
    model_ref = artifact_ref(MODEL_CONTENT)
    day = "2026-09-21T"
    decision_action = {
        "instrument_id": INSTRUMENT,
        "side": "buy",
        "type": "limit",
        "tif": "day",
        "qty": "10",
        "limit_price": "150",
        "purpose": "open",
    }
    not_evaluated = {
        "exit_conviction": None,
        "buy_conviction": None,
        "combined_score": None,
        "outputs_used": [],
        "model_weights": [],
        "clips_applied": [],
    }
    floor = default_floor(DERIVATION)
    bodies = [
        event(
            "opened",
            "StreamOpened",
            f"{day}13:00:00.000000000Z",
            f"{day}13:00:00.000150000Z",
            {"stream_type": "agent", "workspace_id": WORKSPACE, "agent_id": AGENT},
            clock_source="local",
        ),
        event(
            "observation",
            "ObservationRecorded",
            f"{day}13:59:58.000000000Z",
            f"{day}13:59:58.000200000Z",
            {
                "source": "alpaca.iex.quotes",
                "instrument_id": INSTRUMENT,
                "as_of": f"{day}13:59:58.000000000Z",
                "data_ref": quote_ref,
            },
        ),
        event(
            "model_output",
            "ModelOutputRecorded",
            f"{day}13:59:59.000000000Z",
            f"{day}13:59:59.000200000Z",
            {
                "model_id": "quant.mean_reversion",
                "model_version": "1.0.0",
                "content_hash": model_ref,
                "instrument_id": INSTRUMENT,
                "as_of": f"{day}13:59:58.000000000Z",
                "expires_at": "2026-09-22T13:59:58.000000000Z",
                "direction": "long",
                "conviction": "0.97",
                "confidence": "0.98",
                "horizon_s": 86400,
                "thesis_ref": None,
                "evidence": [ID["observation"]],
                "invalidation": None,
                "thesis_id": None,
                "lineage_id": None,
                "ignored": None,
            },
        ),
        event(
            "decision",
            "DecisionMade",
            f"{day}14:00:00.000000000Z",
            f"{day}14:00:00.000100000Z",
            {
                **decision_action,
                "exit_origin": None,
                "exit_conviction": "0.85554",
                "buy_conviction": "0.75554",
                "combined_score": "0.882",
                "outputs_used": [ID["model_output"]],
                "model_weights": [
                    {"key": "quant.mean_reversion", "value": "0.9"},
                    {"key": "quant.momentum", "value": "0.1"},
                ],
                "clips_applied": ["max_order_usd"],
                "dry_run": "allow",
                "reason_code": None,
                "autonomy": "auto",
                "ask_suppressed": None,
            },
        ),
        event(
            "intent",
            "IntentProposed",
            f"{day}14:00:00.000000000Z",
            f"{day}14:00:00.000200000Z",
            dict(decision_action),
            causation_id=ID["decision"],
        ),
        event(
            "owner_close_in_session",
            "OwnerExitRequested",
            f"{day}15:00:00.000000000Z",
            f"{day}15:00:00.000100000Z",
            {
                "scope": "instrument",
                "subject": HELD_INSTRUMENT,
                "confirmed": False,
                "bid": None,
                "bid_size": None,
                "floor": None,
                "user": "user_7f3a",
                "step_up_status": "valid",
                "step_up": {
                    "assertion_id": "stepup_4b2d",
                    "authenticated_at": f"{day}14:59:52.000000000Z",
                    "method": "webauthn",
                },
            },
        ),
        event(
            "owner_close_in_session_intent",
            "IntentProposed",
            f"{day}15:00:00.000000000Z",
            f"{day}15:00:00.000200000Z",
            {
                "instrument_id": HELD_INSTRUMENT,
                "side": "sell",
                "type": "market",
                "tif": "day",
                "qty": DERIVATION["held"]["qty"],
                "limit_price": None,
                "purpose": "owner_exit",
            },
            causation_id=ID["owner_close_in_session"],
        ),
        event(
            "goal_exit",
            "DecisionMade",
            f"{day}20:05:00.000000000Z",
            f"{day}20:05:00.000100000Z",
            {
                "instrument_id": INSTRUMENT,
                "side": "sell",
                "type": "limit",
                "tif": "day",
                "qty": decision_action["qty"],
                "limit_price": first_rung_sell_limit(DERIVATION),
                "purpose": "discretionary_exit",
                "exit_origin": "goal_completion",
                **not_evaluated,
                "dry_run": "defer",
                "reason_code": "discretionary_exit_regular_session_only",
                "autonomy": None,
                "ask_suppressed": None,
            },
        ),
        event(
            "owner_close_confirmed",
            "OwnerExitRequested",
            f"{day}20:10:00.000000000Z",
            f"{day}20:10:00.000100000Z",
            {
                "scope": "instrument",
                "subject": INSTRUMENT,
                "confirmed": True,
                "bid": DERIVATION["owner_bid"],
                "bid_size": "300",
                "floor": floor,
                "user": "user_7f3a",
                "step_up_status": "valid",
                "step_up": {
                    "assertion_id": "stepup_9c1e",
                    "authenticated_at": f"{day}20:09:45.000000000Z",
                    "method": "webauthn",
                },
            },
        ),
        event(
            "owner_close_confirmed_intent",
            "IntentProposed",
            f"{day}20:10:00.000000000Z",
            f"{day}20:10:00.000200000Z",
            {
                "instrument_id": INSTRUMENT,
                "side": "sell",
                "type": "limit",
                "tif": "day",
                "qty": decision_action["qty"],
                "limit_price": floor,
                "purpose": "owner_exit",
            },
            causation_id=ID["owner_close_confirmed"],
        ),
        event(
            "kill_switch_mode",
            "AgentModeChanged",
            f"{day}20:30:00.000000000Z",
            f"{day}20:30:00.000100000Z",
            {"from": "normal", "to": "stopped", "reason": "kill_switch", "lifecycle": "normal"},
        ),
        event(
            "owner_kill_switch",
            "OwnerExitRequested",
            f"{day}20:30:00.000000000Z",
            f"{day}20:30:00.000200000Z",
            {
                "scope": "agent",
                "subject": AGENT,
                "confirmed": False,
                "bid": None,
                "bid_size": None,
                "floor": None,
                "user": "user_7f3a",
                "step_up_status": "absent",
                "step_up": None,
            },
        ),
        event(
            "kill_switch",
            "KillSwitchActivated",
            f"{day}20:30:00.000000000Z",
            f"{day}20:30:00.000300000Z",
            {"scope": "agent", "subject": AGENT, "initiator": "owner", "mode_event": ID["kill_switch_mode"]},
        ),
    ]
    assert [b["seq"] for b in bodies] == list(range(1, len(CHAIN) + 1)), "bodies follow CHAIN's order"
    return bodies


def hash_chain(bodies: list[dict], genesis: str) -> list[dict]:
    entries, prev = [], genesis
    for body in bodies:
        body["prev_hash"] = prev
        text = canon(body)
        prev = sha256_hex(text.encode())
        entries.append(
            {
                "seq": body["seq"],
                "event_type": body["event_type"],
                "body": body,
                "canonical": text,
                "hash": prev,
            }
        )
    return entries


def rechain(entries: list[dict]) -> None:
    """Re-canonicalize and re-hash chain entries in place from the first body's `prev_hash`."""
    prev = entries[0]["body"]["prev_hash"]
    for entry in entries:
        entry["body"]["prev_hash"] = prev
        entry["canonical"] = canon(entry["body"])
        prev = entry["hash"] = sha256_hex(entry["canonical"].encode())


def draft_of(body: dict) -> dict:
    return {k: copy.deepcopy(v) for k, v in body.items() if k not in JOURNAL_FIELDS}


def apply_change(draft: dict, item: dict) -> None:
    *parents, last = item["path"].split(".")
    node = draft
    for name in parents:
        node = node[name]
    if item.get("delete"):
        del node[last]
    else:
        node[last] = copy.deepcopy(item["value"])


def change(path: str, value) -> dict:
    return {"path": path, "value": value}


def delete(path: str) -> dict:
    """The member is absent from the draft, which §4.2 distinguishes from `null`."""
    return {"path": path, "delete": True}


def invalid(name, clause, base, changes, reason, path):
    return {
        "name": name,
        "clause": clause,
        "base_seq": SEQ[base],
        "changes": changes,
        "expect": {"outcome": "Invalid", "reason": reason, "path": path},
    }


def invalid_drafts() -> list[dict]:
    """Each draft breaks exactly one rule; together they cover every §9.1 rule and each DEC-174
    item-3 contradiction the rulings settle."""
    quote = copy.deepcopy(QUOTE_SNAPSHOT)
    as_of = epoch_seconds("2026-09-21T13:59:58.000000000Z")
    stepped_up = epoch_seconds("2026-09-21T20:09:45.000000000Z")
    return [
        invalid(
            "owner_exit_floor_absent",
            "§9.1 absent member",
            "owner_close_confirmed",
            [delete("payload.floor")],
            "schema",
            "payload.floor",
        ),
        invalid(
            "decision_reason_code_absent_on_allow",
            "§9.1 absent member",
            "decision",
            [delete("payload.reason_code")],
            "schema",
            "payload.reason_code",
        ),
        invalid(
            "reason_code_empty_string_on_allow",
            "§4.2",
            "decision",
            [change("payload.reason_code", "")],
            "non_canonical",
            "payload.reason_code",
        ),
        invalid(
            "owner_exit_unconfirmed_empty_user",
            "§4.2",
            "owner_kill_switch",
            [change("payload.user", "")],
            "non_canonical",
            "payload.user",
        ),
        invalid(
            "owner_exit_unconfirmed_without_user",
            "§9.1 OwnerExitRequested",
            "owner_close_in_session",
            [change("payload.user", None)],
            "schema",
            "payload.user",
        ),
        invalid(
            "owner_exit_step_up_status_unknown",
            "§9.1 OwnerExitRequested",
            "owner_kill_switch",
            [change("payload.step_up_status", "failed")],
            "non_canonical",
            "payload.step_up_status",
        ),
        invalid(
            "owner_kill_switch_valid_without_evidence",
            "§9.1 rule 12",
            "owner_kill_switch",
            [change("payload.step_up_status", "valid")],
            "schema",
            "payload.step_up",
        ),
        invalid(
            "owner_exit_stale_with_evidence",
            "§9.1 rule 12",
            "owner_close_in_session",
            [change("payload.step_up_status", "stale")],
            "schema",
            "payload.step_up",
        ),
        invalid(
            "owner_exit_unconfirmed_with_floor",
            "§9.1 rule 12",
            "owner_close_in_session",
            [change("payload.floor", "146.47")],
            "schema",
            "payload.floor",
        ),
        invalid(
            "model_output_as_of_in_seconds",
            "§4.7",
            "model_output",
            [change("payload.as_of", str(as_of))],
            "non_canonical",
            "payload.as_of",
        ),
        invalid(
            "observation_as_of_as_integer",
            "§4.4",
            "observation",
            [change("payload.as_of", as_of)],
            "schema",
            "payload.as_of",
        ),
        invalid(
            "step_up_time_in_seconds",
            "§4.7",
            "owner_close_confirmed",
            [change("payload.step_up.authenticated_at", str(stepped_up))],
            "non_canonical",
            "payload.step_up.authenticated_at",
        ),
        invalid(
            "observation_data_inline",
            "§9.1 artifacts",
            "observation",
            [change("payload.data_ref", quote), change("artifact_refs", [])],
            "schema",
            "payload.data_ref",
        ),
        invalid(
            "observation_artifact_not_listed",
            "§3 artifact_refs",
            "observation",
            [change("artifact_refs", [])],
            "artifact_refs",
            "artifact_refs",
        ),
        invalid(
            "intent_proposed_carries_intent_id",
            "§9.1 IntentProposed",
            "intent",
            [change("payload.intent_id", INTENT_ID)],
            "schema",
            "payload.intent_id",
        ),
        invalid(
            "intent_proposed_protective",
            "§9.1 IntentProposed",
            "intent",
            [change("payload.purpose", "protective")],
            "non_canonical",
            "payload.purpose",
        ),
        invalid(
            "decision_without_mandate_version",
            "§9 required refs",
            "decision",
            [change("config_refs", {})],
            "missing_config_ref",
            "config_refs.mandate_version",
        ),
        invalid(
            "intent_sell_labelled_open",
            "§9.1 rule 1",
            "intent",
            [change("payload.side", "sell")],
            "schema",
            "payload.side",
        ),
        invalid(
            "intent_limit_without_price",
            "§9.1 rule 2",
            "intent",
            [change("payload.limit_price", None)],
            "schema",
            "payload.limit_price",
        ),
        invalid(
            "decision_market_exit_with_price",
            "§9.1 rule 2",
            "decision",
            [
                change("payload.side", "sell"),
                change("payload.type", "market"),
                change("payload.purpose", "discretionary_exit"),
                change("payload.exit_origin", "signal"),
            ],
            "schema",
            "payload.limit_price",
        ),
        invalid(
            "intent_market_open",
            "§9.1 rule 3",
            "intent",
            [change("payload.type", "market"), change("payload.limit_price", None)],
            "schema",
            "payload.type",
        ),
        invalid(
            "decision_allow_with_reason_code",
            "§9.1 rule 4",
            "decision",
            [change("payload.reason_code", "insufficient_buying_power")],
            "schema",
            "payload.reason_code",
        ),
        invalid(
            "decision_deny_with_autonomy",
            "§9.1 rule 5",
            "decision",
            [change("payload.dry_run", "deny"), change("payload.reason_code", "insufficient_buying_power")],
            "schema",
            "payload.autonomy",
        ),
        invalid(
            "decision_defer_on_open",
            "§9.1 rule 6",
            "decision",
            [
                change("payload.dry_run", "defer"),
                change("payload.reason_code", "session_not_allowed"),
                change("payload.autonomy", None),
            ],
            "schema",
            "payload.dry_run",
        ),
        invalid(
            "decision_exit_classified_ask",
            "§9.1 rule 7",
            "decision",
            [
                change("payload.side", "sell"),
                change("payload.purpose", "discretionary_exit"),
                change("payload.exit_origin", "signal"),
                change("payload.autonomy", "ask"),
            ],
            "schema",
            "payload.autonomy",
        ),
        invalid(
            "decision_auto_with_ask_suppressed",
            "§9.1 rule 7",
            "decision",
            [change("payload.ask_suppressed", "budget")],
            "schema",
            "payload.ask_suppressed",
        ),
        invalid(
            "decision_ask_suppressed_unknown_reason",
            "§9.1 DecisionMade",
            "decision",
            [change("payload.autonomy", "ask"), change("payload.ask_suppressed", "quiet_hours")],
            "non_canonical",
            "payload.ask_suppressed",
        ),
        invalid(
            "decision_discretionary_exit_without_origin",
            "§9.1 rule 8",
            "goal_exit",
            [change("payload.exit_origin", None)],
            "schema",
            "payload.exit_origin",
        ),
        invalid(
            "decision_open_with_exit_origin",
            "§9.1 rule 8",
            "decision",
            [change("payload.exit_origin", "signal")],
            "schema",
            "payload.exit_origin",
        ),
        invalid(
            "decision_exit_origin_unknown",
            "§9.1 DecisionMade",
            "goal_exit",
            [change("payload.exit_origin", "profit_stop")],
            "non_canonical",
            "payload.exit_origin",
        ),
        invalid(
            "decision_goal_exit_with_conviction",
            "§9.1 rule 8",
            "goal_exit",
            [change("payload.exit_conviction", "0.1")],
            "schema",
            "payload.exit_conviction",
        ),
        invalid(
            "decision_goal_exit_with_outputs",
            "§9.1 rule 8",
            "goal_exit",
            [change("payload.outputs_used", [ID["model_output"]])],
            "schema",
            "payload.outputs_used",
        ),
        invalid(
            "decision_signal_exit_without_convictions",
            "§9.1 rule 8",
            "goal_exit",
            [change("payload.exit_origin", "signal")],
            "schema",
            "payload.exit_conviction",
        ),
        invalid(
            "decision_risk_exit_with_convictions",
            "§9.1 rule 8",
            "decision",
            [change("payload.side", "sell"), change("payload.purpose", "risk_exit")],
            "schema",
            "payload.exit_conviction",
        ),
        invalid(
            "decision_outputs_repeated",
            "§9.1 rule 9",
            "decision",
            [change("payload.outputs_used", [ID["model_output"], ID["model_output"]])],
            "non_canonical",
            "payload.outputs_used",
        ),
        invalid(
            "decision_weights_unsorted",
            "§9.1 rule 9",
            "decision",
            [
                change(
                    "payload.model_weights",
                    [
                        {"key": "quant.momentum", "value": "0.1"},
                        {"key": "quant.mean_reversion", "value": "0.9"},
                    ],
                )
            ],
            "non_canonical",
            "payload.model_weights",
        ),
        invalid(
            "decision_clips_out_of_order",
            "§9.1 rule 9",
            "decision",
            [change("payload.clips_applied", ["position_cap", "max_order_usd"])],
            "non_canonical",
            "payload.clips_applied",
        ),
        invalid(
            "intent_without_causation",
            "§9.1 rule 10",
            "intent",
            [change("causation_id", None)],
            "schema",
            "causation_id",
        ),
        invalid(
            "mode_looser_than_lifecycle",
            "§9.1 rule 11",
            "kill_switch_mode",
            [change("payload.to", "exits_only"), change("payload.lifecycle", "paused")],
            "schema",
            "payload.to",
        ),
        invalid(
            "mode_lifecycle_exits_only",
            "§9.1 AgentModeChanged",
            "kill_switch_mode",
            [change("payload.lifecycle", "exits_only")],
            "non_canonical",
            "payload.lifecycle",
        ),
        invalid(
            "owner_exit_confirmed_without_floor",
            "§9.1 rule 12",
            "owner_close_confirmed",
            [change("payload.floor", None)],
            "schema",
            "payload.floor",
        ),
        invalid(
            "owner_exit_unconfirmed_with_bid",
            "§9.1 rule 12",
            "owner_close_confirmed",
            [change("payload.confirmed", False)],
            "schema",
            "payload.bid",
        ),
        invalid(
            "model_output_lineage_without_thesis",
            "§9.1 rule 13",
            "model_output",
            [change("payload.lineage_id", "lin_01")],
            "schema",
            "payload.thesis_id",
        ),
        invalid(
            "stream_opened_other_agent",
            "§9.1 rule 14",
            "opened",
            [change("payload.agent_id", "agent_b")],
            "stream_mismatch",
            "stream_id",
        ),
        invalid(
            "kill_switch_other_agent",
            "§9.1 rule 15",
            "kill_switch",
            [change("payload.subject", "agent_b")],
            "stream_mismatch",
            "payload.subject",
        ),
        invalid(
            "kill_switch_other_workspace",
            "§9.1 rule 15",
            "kill_switch",
            [change("payload.scope", "workspace"), change("payload.subject", "ws_01J8Z9")],
            "stream_mismatch",
            "payload.subject",
        ),
        invalid(
            "owner_exit_other_agent",
            "§9.1 rule 15",
            "owner_kill_switch",
            [change("payload.subject", "agent_b")],
            "stream_mismatch",
            "payload.subject",
        ),
    ]


def valid(name, clause, base, changes):
    return {
        "name": name,
        "clause": clause,
        "base_seq": SEQ[base],
        "changes": changes,
        "expect": {"outcome": "Valid"},
    }


def valid_drafts() -> list[dict]:
    """Drafts a rule might be misread to refuse. Each must be accepted: refusing an owner exit, or the
    owner's pause or Stop, would hold a reduction (`AGENTS.md` rule 13), and refusing a suppressed
    ask would leave the skip unrecorded (DEC-156 item 5). The owner's mode changes put `to` equal to
    `lifecycle`, rule 11's boundary."""
    return [
        valid(
            "mode_owner_pause",
            "§9.1 rule 11",
            "kill_switch_mode",
            [
                change("payload.to", "paused"),
                change("payload.reason", "owner_pause"),
                change("payload.lifecycle", "paused"),
            ],
        ),
        valid(
            "mode_owner_resume",
            "§9.1 rule 11",
            "kill_switch_mode",
            [
                change("payload.from", "paused"),
                change("payload.to", "normal"),
                change("payload.reason", "owner_resume"),
                change("payload.lifecycle", "normal"),
            ],
        ),
        valid(
            "mode_owner_stop",
            "§9.1 rule 11",
            "kill_switch_mode",
            [
                change("payload.to", "stopped"),
                change("payload.reason", "owner_stop"),
                change("payload.lifecycle", "stopped"),
            ],
        ),
        valid(
            "decision_ask_suppressed_by_budget",
            "§9.1 rule 7",
            "decision",
            [change("payload.autonomy", "ask"), change("payload.ask_suppressed", "budget")],
        ),
        valid(
            "decision_removed_instrument_exit_without_numbers",
            "§9.1 rule 8",
            "goal_exit",
            [change("payload.exit_origin", "removed_instrument")],
        ),
        valid(
            "owner_close_confirmed_bid_stale_step_up",
            "§9.1 OwnerExitRequested",
            "owner_close_confirmed",
            [change("payload.step_up_status", "stale"), change("payload.step_up", None)],
        ),
        valid(
            "owner_kill_switch_confirmed_bid_without_step_up",
            "§9.1 OwnerExitRequested",
            "owner_kill_switch",
            [
                change("payload.confirmed", True),
                change("payload.bid", DERIVATION["owner_bid"]),
                change("payload.bid_size", "300"),
                change("payload.floor", default_floor(DERIVATION)),
            ],
        ),
        valid(
            "owner_kill_switch_stale_step_up",
            "§9.1 OwnerExitRequested",
            "owner_kill_switch",
            [change("payload.step_up_status", "stale")],
        ),
    ]


def batch(name, clause, members, expect):
    return {
        "name": name,
        "clause": clause,
        "drafts": [{"base_seq": SEQ[base], "changes": changes} for base, changes in members],
        "expect": expect,
    }


def batches() -> tuple[list[dict], list[dict]]:
    """Rule 10's second clause: a `DecisionMade` and its `IntentProposed` in one `append` batch."""

    def refused(path: str) -> dict:
        return {"outcome": "Invalid", "reason": "schema", "path": path, "draft_index": 1}

    accepted = [batch("decision_and_its_intent", "§9.1 rule 10", [("decision", []), ("intent", [])], {"outcome": "Valid"})]
    rejected = [
        batch(
            "intent_quantity_differs_from_its_decision",
            "§9.1 rule 10",
            [("decision", []), ("intent", [change("payload.qty", "11")])],
            refused("payload.qty"),
        ),
        batch(
            "intent_limit_differs_from_its_decision",
            "§9.1 rule 10",
            [("decision", []), ("intent", [change("payload.limit_price", "150.01")])],
            refused("payload.limit_price"),
        ),
        batch(
            "intent_purpose_differs_from_its_decision",
            "§9.1 rule 10",
            [("decision", []), ("intent", [change("payload.purpose", "increase")])],
            refused("payload.purpose"),
        ),
    ]
    return accepted, rejected


def range_case(name, clause, changes, code, at):
    return {
        "name": name,
        "clause": clause,
        "from_seq": 1,
        "changes": [{"seq": SEQ[base], "path": path, "value": value} for base, path, value in changes],
        "expect": {"code": code, "seq": SEQ[at]},
    }


def range_verification() -> list[dict]:
    """§11's per-range checks across agent-stream events. Each case applies its changes to the
    chain's bodies, re-chains from the genesis hash, and verifies from `from_seq`: every per-event
    check passes and the range check fails once, at the listed seq, with the listed code. Each
    `mode_event_mismatch` case breaks one of its three clauses: the named event is an
    `AgentModeChanged`, its reason is `kill_switch`, and on a full-chain run it exists."""
    return [
        range_case(
            "intent_repeats_another_action",
            "§11 intent_action_mismatch",
            [("intent", "payload.qty", "11")],
            "intent_action_mismatch",
            "intent",
        ),
        range_case(
            "kill_switch_names_the_owner_command",
            "§11 mode_event_mismatch",
            [("kill_switch", "payload.mode_event", ID["owner_kill_switch"])],
            "mode_event_mismatch",
            "kill_switch",
        ),
        range_case(
            "kill_switch_names_an_owner_pause",
            "§11 mode_event_mismatch",
            [
                ("kill_switch_mode", "payload.to", "paused"),
                ("kill_switch_mode", "payload.reason", "owner_pause"),
                ("kill_switch_mode", "payload.lifecycle", "paused"),
            ],
            "mode_event_mismatch",
            "kill_switch",
        ),
        range_case(
            "kill_switch_names_no_event_on_the_full_chain",
            "§11 mode_event_mismatch",
            [("kill_switch", "payload.mode_event", ABSENT_EVENT_ID)],
            "mode_event_mismatch",
            "kill_switch",
        ),
    ]


def tampered_chain(chain: list[dict], case: dict) -> list[dict]:
    entries = copy.deepcopy(chain)
    for item in case["changes"]:
        apply_change(entries[item["seq"] - 1]["body"], item)
    rechain(entries)
    return entries


def batch_drafts(chain: list[dict], case: dict) -> list[dict]:
    return [apply_changes(chain, member) for member in case["drafts"]]


def batch_matches(got: list[tuple[int, Violation]], want: dict) -> bool:
    if want["outcome"] == "Valid":
        return not got
    return len(got) == 1 and (got[0][0], got[0][1].reason, got[0][1].path) == (
        want["draft_index"],
        want["reason"],
        want["path"],
    )


def apply_changes(chain: list[dict], case: dict) -> dict:
    draft = draft_of(chain[case["base_seq"] - 1]["body"])
    for item in case["changes"]:
        apply_change(draft, item)
    return draft


# --------------------------------------------------------------------------- independent oracles


def dec(text: str) -> Decimal:
    return Decimal(text)


def round12(value: Decimal) -> str:
    with localcontext() as ctx:
        ctx.prec = 60
        return normalize_decimal(str(value.quantize(Decimal("1e-12"), rounding=ROUND_HALF_EVEN)))


def recompute_decision(chain: list[dict], artifacts: list[dict], d: dict) -> dict:
    """Mandate spec §8.3 from the journaled outputs, the observed quote, and the illustrative inputs,
    computed without the vector's own numbers: the members `DecisionMade` must carry."""
    now = parse_instant(d["now"])[0]
    observation = next(e["body"]["payload"] for e in chain if e["event_type"] == "ObservationRecorded")
    quote = next(a["object"] for a in artifacts if a["ref"] == observation["data_ref"])
    ask = dec(quote["ask"])
    outputs = {e["body"]["payload"]["model_id"]: e for e in chain if e["event_type"] == "ModelOutputRecorded"}
    weights = {m["model_id"]: dec(m["weight"]) for m in d["models"]}
    total = sum(weights.values())
    fresh, missing = {}, Decimal(0)
    for model in d["models"]:
        entry = outputs.get(model["model_id"])
        if entry is None:
            missing += weights[model["model_id"]]
            continue
        p = entry["body"]["payload"]
        as_of, expires = parse_instant(p["as_of"])[0], parse_instant(p["expires_at"])[0]
        if as_of <= now < expires and (now - as_of).total_seconds() <= model["max_output_age_s"]:
            fresh[model["model_id"]] = (entry["body"]["event_id"], p)
        else:
            missing += weights[model["model_id"]]
    f = sum(weights[m] * dec(p["conviction"]) * dec(p["confidence"]) for m, (_, p) in fresh.items())
    score = sum(weights[m] * dec(p["confidence"]) for m, (_, p) in fresh.items())
    exit_c, buy_c = f / total, (f - missing) / total
    assert exit_c > -dec(d["exit_threshold"]), "the vector is an entry, not an exit"
    assert buy_c >= dec(d["entry_threshold"]), "the vector must clear the entry threshold"
    cap = min(dec(d["max_position_usd"]), dec(d["max_position_fraction"]) * dec(d["equity"]))
    target = buy_c * cap * dec(d["size_factor"])
    held = dec(d["market_value"]) + dec(d["working_opening_cost"])
    delta = target - held
    band = dec(d["rebalance_band"]) * cap
    assert delta > 0 and delta >= band, "the vector must not hold"
    bounds = [
        ("max_order_usd", dec(d["max_order_usd"])),
        ("position_cap", cap - held),
        (
            "gross_exposure_cap",
            min(dec(d["max_gross_exposure_usd"]), dec(d["equity"]))
            - dec(d["held"]["qty"]) * dec(d["held"]["mark"]),
        ),
    ]
    value, clips = delta, []
    for name, bound in bounds:
        if bound < value:
            value, clips = bound, [*clips, name]
    assert value >= band, "the clipped value must not fall below the band"
    step = dec(d["increment"])
    qty = (value / ask / step).to_integral_value(rounding=ROUND_DOWN) * step
    assert qty >= dec(d["min_order_qty"])
    return {
        "instrument_id": next(iter(fresh.values()))[1]["instrument_id"],
        "side": "buy",
        "type": "limit",
        "tif": d["tif"],
        "qty": normalize_decimal(str(qty)),
        "limit_price": normalize_decimal(quote["ask"]),
        "purpose": "open" if held == 0 else "increase",
        "exit_conviction": round12(exit_c),
        "buy_conviction": round12(buy_c),
        "combined_score": round12(score / total),
        "outputs_used": sorted(event_id for event_id, _ in fresh.values()),
        "model_weights": [{"key": k, "value": normalize_decimal(str(weights[k]))} for k in sorted(weights)],
        "clips_applied": clips,
        "exit_origin": None,
        "dry_run": d["dry_run"],
        "reason_code": None,
        "autonomy": d["autonomy"],
        "ask_suppressed": None,
    }


def nanos(text: str) -> int:
    instant, fraction = parse_instant(text)
    return calendar.timegm(instant.timetuple()) * 10**9 + fraction


@functools.cache
def outside_session_exit_defer_code() -> str:
    """The reason code the trading-domain reference cases give a discretionary exit the gate defers:
    read from those cases, never from this generator's vectors, and registered as a reason code."""
    cases = yaml.safe_load(TRADING_CASES.read_text(encoding="utf-8"))
    codes = {
        step["expect"]["decision"]["reason_code"]
        for case in cases["cases"]
        for step in case.get("steps", [])
        if step.get("event") == "propose_order"
        and step["data"].get("purpose") == "discretionary_exit"
        and step.get("expect", {}).get("decision", {}).get("verdict") == "defer"
    }
    assert len(codes) == 1 and codes <= set(cases["reason_codes"]), f"one registered defer code, got {codes}"
    return codes.pop()


def check_goal_exit(chain: list[dict], d: dict, decision: dict, goal: dict) -> list[str]:
    """Mandate spec §3.1, §6.2 and trading spec §9.4, §9.6 for the goal-completion exit, from the
    derivation: what it sells, at what price, that it is deferred after the session with the
    trading cases' defer code, and that nothing is proposed."""
    problems = []
    p = goal["payload"]
    whole = (decision["payload"]["instrument_id"], "sell", decision["payload"]["qty"])
    if d["goal"] != "profit_stop" or (p["instrument_id"], p["side"], p["qty"]) != whole:
        problems.append("the profit_stop completion does not exit the whole position")
    if (p["purpose"], p["exit_origin"]) != ("discretionary_exit", "goal_completion"):
        problems.append("a goal completion's exit is a discretionary exit of origin goal_completion")
    close = nanos(d["regular_session_utc"]["close"])
    if nanos(goal["event_time"]) >= close:
        code = outside_session_exit_defer_code()
        if (p["dry_run"], p["reason_code"]) != ("defer", code):
            problems.append(f"after the session a discretionary equity exit is deferred ({code})")
        tick = Fraction(d["equity_tick"])
        rung = Fraction(d["goal_exit_reference_bid"]) * (1 - Fraction(d["exit_offset"]))
        limit = math.ceil(rung / tick) * tick
        if p["type"] != "limit" or p["limit_price"] is None or Fraction(p["limit_price"]) != limit:
            problems.append("outside the session the exit is a limit at the ladder's first rung (§9.4, §5.6)")
    if any(e["body"]["causation_id"] == goal["event_id"] for e in chain):
        problems.append("a deferred decision proposes nothing (mandate spec §6.2)")
    evaluated = ("exit_conviction", "buy_conviction", "combined_score", "outputs_used", "model_weights", "clips_applied")
    if any(p[m] not in (None, []) for m in evaluated):
        problems.append("no order-builder evaluation produced the goal exit, so it carries none of its results")
    return problems


def check_owner_exits(chain: list[dict], d: dict, decision: dict) -> list[str]:
    """Trading spec §5.5 and DEC-158 option (c), from the derivation rather than the validator: who
    asked, with which step-up, and what each owner exit may and may not do."""
    problems = []
    bodies = [e["body"] for e in chain]
    positions = {d["held"]["instrument_id"]: d["held"]["qty"], decision["payload"]["instrument_id"]: decision["payload"]["qty"]}
    session = nanos(d["regular_session_utc"]["open"]), nanos(d["regular_session_utc"]["close"])
    for owner in (b for b in bodies if b["event_type"] == "OwnerExitRequested"):
        p, at = owner["payload"], nanos(owner["event_time"])
        label = f"OwnerExitRequested seq {owner['seq']}"
        if p["user"] is None:
            problems.append(f"{label}: the owner who asked is not recorded")
        evidence = p["step_up"]
        if (evidence is not None) != (p["step_up_status"] == "valid"):
            problems.append(f"{label}: step_up does not match step_up_status")
        if evidence is not None and not 0 <= at - nanos(evidence["authenticated_at"]) <= d["step_up_max_age_s"] * 10**9:
            problems.append(f"{label}: step-up recorded as valid is not fresh at the command (DEC-156 item 8)")
        caused = [b for b in bodies if b["event_type"] == "IntentProposed" and b["causation_id"] == owner["event_id"]]
        in_session = session[0] <= at < session[1]
        if p["scope"] != "instrument":
            if caused:
                problems.append(f"{label}: a kill switch's flatten is never a proposed intent (§9.1)")
            continue
        if len(caused) != 1:
            problems.append(f"{label}: an owner close of one instrument proposes exactly one intent")
            continue
        close = caused[0]["payload"]
        if (close["instrument_id"], close["side"], close["purpose"]) != (p["subject"], "sell", "owner_exit"):
            problems.append(f"{label}: its intent is not an owner_exit sell of the named instrument")
        if close["qty"] != positions.get(p["subject"]):
            problems.append(f"{label}: its intent does not close the whole position")
        if p["confirmed"]:
            floor = dec(d["owner_bid"]) * (1 - dec(d["max_exit_offset"]))
            if p["bid"] != d["owner_bid"] or dec(p["floor"]) != floor:
                problems.append(f"{label}: the floor is not the default floor of its confirmed bid")
            if close["type"] != "limit" or close["limit_price"] is None or dec(close["limit_price"]) < floor:
                problems.append(f"{label}: its intent may price below the confirmed floor")
            if in_session:
                problems.append(f"{label}: the vector's confirmed close is meant to be outside the session")
        elif not in_session:
            problems.append(f"{label}: without a confirmed bid an equity owner close sells only in the session")
    return problems


def check_chain(section: dict, v3: dict) -> list[str]:
    """Cross-event facts no single draft check can see. Returns every failure, so seeded bugs can be
    shown to be caught."""
    problems = []
    chain = section["chain"]
    prev = v3["genesis_prev_hash"]
    for i, entry in enumerate(chain, start=1):
        body = entry["body"]
        if body["seq"] != i or entry["seq"] != i:
            problems.append(f"seq {i}: gap")
        if body["prev_hash"] != prev:
            problems.append(f"seq {i}: prev_hash does not chain")
        if canon(body) != entry["canonical"]:
            problems.append(f"seq {i}: canonical differs")
        if sha256_hex(entry["canonical"].encode()) != entry["hash"]:
            problems.append(f"seq {i}: hash differs")
        prev = entry["hash"]
        if body["stream_id"] != STREAM or body["event_type"] != entry["event_type"]:
            problems.append(f"seq {i}: stream or type differs")
    stored = {a["ref"]: a for a in section["artifacts"]}
    for a in section["artifacts"]:
        if (
            canon(a["object"]) != a["canonical"]
            or "sha256:" + sha256_hex(a["canonical"].encode()) != a["ref"]
        ):
            problems.append(f"artifact {a['name']}: does not re-hash")
    for entry in chain:
        for ref in entry["body"]["artifact_refs"]:
            if ref not in stored:
                problems.append(f"seq {entry['seq']}: artifact {ref} missing")
    if chain[0]["event_type"] != "StreamOpened":
        problems.append("seq 1 is not StreamOpened")
    named = {name: chain[seq - 1]["body"] for name, seq in SEQ.items() if seq <= len(chain)}
    decision = named["decision"]
    expected = recompute_decision(chain, section["artifacts"], section["derivation"])
    for member, value in expected.items():
        if decision["payload"][member] != value:
            problems.append(f"DecisionMade.{member}: {decision['payload'][member]!r} != recomputed {value!r}")
    intent = named["intent"]
    if intent["causation_id"] != decision["event_id"]:
        problems.append("IntentProposed.causation_id is not the DecisionMade")
    action = {k: decision["payload"][k] for k in intent["payload"]}
    if intent["payload"] != action:
        problems.append("IntentProposed does not repeat the DecisionMade's action")
    received = next(e["body"] for e in v3["chain"] if e["event_type"] == "IntentReceived")
    copied = {k: v for k, v in received["payload"].items() if k not in ("intent_id", "agent_id")}
    if intent["payload"] != copied:
        problems.append("IntentProposed differs from the IntentReceived vector less intent_id and agent_id")
    if (
        received["payload"]["intent_id"] != intent["event_id"]
        or received["causation_id"] != intent["event_id"]
    ):
        problems.append("IntentReceived does not name the IntentProposed as its intent")
    if received["payload"]["agent_id"] != intent["stream_id"].split(":")[2]:
        problems.append("IntentReceived.agent_id is not the agent stream's agent")
    if not intent["recorded_at"] < received["recorded_at"]:
        problems.append("IntentProposed must be recorded before the account stream copies it")
    mode, switch = named["kill_switch_mode"], named["kill_switch"]
    if switch["payload"]["mode_event"] != mode["event_id"] or mode["payload"]["reason"] != "kill_switch":
        problems.append("KillSwitchActivated.mode_event does not name its AgentModeChanged")
    if mode["payload"]["to"] != "stopped":
        problems.append("an owner kill switch's final mode is stopped (trading spec §5.5)")
    problems += check_goal_exit(chain, section["derivation"], decision, named["goal_exit"])
    problems += check_owner_exits(chain, section["derivation"], decision)
    for case in section["invalid_drafts"]:
        got = violations(apply_changes(chain, case))
        want = case["expect"]
        if len(got) != 1 or (got[0].reason, got[0].path) != (want["reason"], want["path"]):
            problems.append(f"{case['name']}: expected exactly {want['reason']} at {want['path']}, got {got}")
    for case in section["valid_drafts"]:
        got = violations(apply_changes(chain, case))
        if got:
            problems.append(f"{case['name']}: expected Valid, got {got}")
    for case in section["valid_batches"] + section["invalid_batches"]:
        got = batch_violations(batch_drafts(chain, case))
        if not batch_matches(got, case["expect"]):
            problems.append(f"batch {case['name']}: expected {case['expect']}, got {got}")
    if verify_range(chain, 1):
        problems.append(f"the chain fails §11's range checks: {verify_range(chain, 1)}")
    for case in section["range_verification"]:
        want = [(case["expect"]["seq"], case["expect"]["code"])]
        tampered = tampered_chain(chain, case)
        got = verify_range(tampered, case["from_seq"])
        if got != want:
            problems.append(f"range case {case['name']}: expected {want}, got {got}")
        for entry in tampered:
            if violations(draft_of(entry["body"])):
                problems.append(f"range case {case['name']}: seq {entry['seq']} is not a valid draft")
    for entry in chain:
        got = violations(draft_of(entry["body"]))
        if got:
            problems.append(f"seq {entry['seq']}: valid event breaks {got}")
    return problems


VALIDATOR_MUTANTS = (
    "record.extra",
    "record.missing",
    "types.str_nonempty",
    "types.timestamp",
    "artifact_refs",
    "config_refs.required",
    *(f"rule.{n}" for n in range(1, 15)),
    "rule.7.ask_suppressed",
    "rule.8.exit_origin",
    "rule.12.step_up",
    "rule.15.agent",
    "rule.15.workspace",
    *REGRESSIONS,
    "regress.rule_12_ties_evidence_to_the_bid",
    "regress.rule_8_numbers_on_every_exit_but_risk",
    "boundary.rule_11_strictly_stricter",
    "rule.10.batch",
    "verify.intent_action_mismatch",
    "verify.mode_event_mismatch.event_type",
    "verify.mode_event_mismatch.reason",
    "verify.mode_event_mismatch.unresolved",
)


def draft_named(section: dict, name: str) -> dict:
    return next(d for d in section["invalid_drafts"] if d["name"] == name)


def body_named(section: dict, name: str) -> dict:
    return section["chain"][SEQ[name] - 1]["body"]


def payload_named(section: dict, name: str) -> dict:
    return body_named(section, name)["payload"]


def vector_mutants(section: dict) -> list[tuple[str, dict]]:
    """Seeded bugs in the vectors; the chain check must reject each one."""

    unhashed = {"prev_hash not chained", "artifact content changed"}

    def mutated(name: str, fn) -> dict:
        """The mutant, re-chained unless it seeds a hashing bug, so that only the check it names can
        catch it rather than the canonical-bytes check."""
        copy_ = copy.deepcopy(section)
        fn(copy_)
        if name not in unhashed:
            rechain(copy_["chain"])
        return copy_

    def decision(s: dict) -> dict:
        return payload_named(s, "decision")

    out = []
    for name, fn in [
        (
            "missing model counted as 0 in buy conviction",
            lambda s: decision(s).update(buy_conviction=decision(s)["exit_conviction"]),
        ),
        ("combined score from conviction", lambda s: decision(s).update(combined_score="0.8536")),
        (
            "every bound listed as a clip",
            lambda s: decision(s).update(clips_applied=["max_order_usd", "position_cap", "gross_exposure_cap"]),
        ),
        ("quantity not truncated", lambda s: decision(s).update(qty="10.07")),
        (
            "weights of fresh models only",
            lambda s: decision(s).update(model_weights=[{"key": "quant.mean_reversion", "value": "0.9"}]),
        ),
        ("intent differs from its decision", lambda s: payload_named(s, "intent").update(qty="11")),
        (
            "intent caused by the model output",
            lambda s: body_named(s, "intent").update(causation_id=ID["model_output"]),
        ),
        ("prev_hash not chained", lambda s: body_named(s, "owner_close_in_session").update(prev_hash="0" * 64)),
        ("artifact content changed", lambda s: s["artifacts"][0]["object"].update(ask="150.02")),
        ("floor not the default", lambda s: payload_named(s, "owner_close_confirmed").update(floor="146.46")),
        (
            "mode_event names another event",
            lambda s: payload_named(s, "kill_switch").update(mode_event=ID["owner_kill_switch"]),
        ),
        ("goal exit of part of the position", lambda s: payload_named(s, "goal_exit").update(qty="4")),
        (
            "goal exit allowed after the session",
            lambda s: payload_named(s, "goal_exit").update(dry_run="allow", reason_code=None, autonomy="auto"),
        ),
        (
            "goal exit deferred with the opening's deny code",
            lambda s: payload_named(s, "goal_exit").update(reason_code="session_not_allowed"),
        ),
        (
            "goal exit sent as a market order after the session",
            lambda s: payload_named(s, "goal_exit").update(type="market", limit_price=None),
        ),
        (
            "goal exit limit rounded down, not up",
            lambda s: payload_named(s, "goal_exit").update(limit_price="150.24"),
        ),
        (
            "goal exit carries the order builder's weights",
            lambda s: payload_named(s, "goal_exit").update(model_weights=decision(s)["model_weights"]),
        ),
        (
            "deferred goal exit proposes an intent",
            lambda s: body_named(s, "owner_close_confirmed_intent").update(causation_id=ID["goal_exit"]),
        ),
        (
            "confirmed close priced below its floor",
            lambda s: payload_named(s, "owner_close_confirmed_intent").update(limit_price="146.46"),
        ),
        (
            "owner close of part of the position",
            lambda s: payload_named(s, "owner_close_in_session_intent").update(qty="4"),
        ),
        (
            "unconfirmed close after the session closes",
            lambda s: body_named(s, "owner_close_in_session").update(event_time="2026-09-21T20:05:00.000000000Z")
            or payload_named(s, "owner_close_in_session")["step_up"].update(
                authenticated_at="2026-09-21T20:04:52.000000000Z"
            ),
        ),
        (
            "stale step-up recorded as valid",
            lambda s: payload_named(s, "owner_close_confirmed")["step_up"].update(
                authenticated_at="2026-09-21T20:04:59.000000000Z"
            ),
        ),
        (
            "kill switch flatten proposed as an intent",
            lambda s: body_named(s, "owner_close_confirmed_intent").update(causation_id=ID["owner_kill_switch"]),
        ),
        (
            "invalid draft expects the wrong reason",
            lambda s: draft_named(s, "reason_code_empty_string_on_allow")["expect"].update(reason="schema"),
        ),
    ]:
        out.append((name, mutated(name, fn)))
    return out


def run_mutants(section: dict, v3: dict) -> list[str]:
    escaped = []
    chain = section["chain"]
    cases = [(draft_of(e["body"]), None) for e in chain]
    cases += [(apply_changes(chain, c), None) for c in section["valid_drafts"]]
    cases += [(apply_changes(chain, c), c["expect"]) for c in section["invalid_drafts"]]
    batch_cases = [(batch_drafts(chain, c), c["expect"]) for c in section["valid_batches"] + section["invalid_batches"]]
    range_cases = [(tampered_chain(chain, c), c) for c in section["range_verification"]]
    for mutant in VALIDATOR_MUTANTS:
        skip = frozenset([mutant])
        caught = False
        for draft, want in cases:
            got = violations(draft, skip)
            if want is None:
                caught |= bool(got)
            else:
                caught |= len(got) != 1 or (got[0].reason, got[0].path) != (want["reason"], want["path"])
        for drafts, want in batch_cases:
            caught |= not batch_matches(batch_violations(drafts, skip), want)
        for entries, case in range_cases:
            want = [(case["expect"]["seq"], case["expect"]["code"])]
            caught |= verify_range(entries, case["from_seq"], skip) != want
        caught |= bool(verify_range(chain, 1, skip))
        if not caught:
            escaped.append(f"validator mutant {mutant}")
    for name, mutated in vector_mutants(section):
        if not check_chain(mutated, v3):
            escaped.append(f"vector mutant: {name}")
    return escaped


# --------------------------------------------------------------------------- output


def build_section(v3: dict) -> dict:
    chain = hash_chain(chain_bodies(), v3["genesis_prev_hash"])
    artifacts = [
        {"name": name, "ref": artifact_ref(obj), "object": obj, "canonical": canon(obj)}
        for name, obj in ARTIFACTS.items()
    ]
    return {
        "spec": "docs/specs/journal.md v0.5 §9.1 (DEC-177)",
        "stream_id": STREAM,
        "artifacts": artifacts,
        "chain": chain,
        "derivation": DERIVATION,
        "invalid_drafts": invalid_drafts(),
        "valid_drafts": valid_drafts(),
        "valid_batches": batches()[0],
        "invalid_batches": batches()[1],
        "range_verification": range_verification(),
    }


class Dumper(yaml.SafeDumper):
    pass


def split_file(text: str) -> tuple[str, str | None]:
    head, found, tail = text.partition(MARKER + "\n")
    return (head, tail) if found else (text, None)


def render(v3_text: str, section: dict) -> str:
    head, _ = split_file(v3_text)
    body = yaml.dump(
        {"agent_stream": section},
        Dumper=Dumper,
        sort_keys=False,
        allow_unicode=True,
        width=10**6,
        default_flow_style=False,
    )
    return head.rstrip("\n") + "\n" + MARKER + "\n" + body


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="fail if journal.yaml is not what this generates")
    mode.add_argument("--write", action="store_true", help="rewrite the agent_stream section (the default)")
    parser.add_argument("--vectors", type=Path, default=VECTORS, help="the journal.yaml to read or write")
    args = parser.parse_args(argv)
    vectors: Path = args.vectors

    text = vectors.read_text(encoding="utf-8")
    v3 = yaml.safe_load(split_file(text)[0])
    self_test(v3)
    section = build_section(v3)

    problems = check_chain(section, v3)
    problems += run_mutants(section, v3)
    for problem in problems:
        print(f"FAIL {problem}", file=sys.stderr)
    if problems:
        return 1

    rendered = render(text, section)
    reread = yaml.safe_load(rendered)["agent_stream"]
    if check_chain(reread, v3):
        print("FAIL the rendered YAML does not read back to the same vectors", file=sys.stderr)
        return 1
    if args.check:
        if rendered != text:
            print(f"FAIL {vectors} differs; run reference/journal/generate.py", file=sys.stderr)
            return 1
    else:
        vectors.write_text(rendered, encoding="utf-8")
    print(
        f"ok: v3 vectors reproduced; {len(section['chain'])} agent-stream events, "
        f"{len(section['invalid_drafts'])} invalid and {len(section['valid_drafts'])} valid drafts, "
        f"{len(section['invalid_batches']) + len(section['valid_batches'])} batches, "
        f"{len(section['range_verification'])} range cases; {len(VALIDATOR_MUTANTS)} validator and "
        f"{len(vector_mutants(section))} vector mutants caught"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
