"""Generates the agent-stream vectors of docs/specs/reference-cases/journal.yaml (DEC-177).

Journal spec §9.1 closes the agent stream's payload schemas; this script is their reference
implementation. It:

1. canonicalizes per spec §4 and proves it by reproducing every version-3 vector (chain bodies and
   hashes, the export line, string escaping, and decimal normalization) before trusting itself;
2. builds the artifacts and the agent-stream chain, hashing each body onto the previous one;
3. validates every draft against the closed schemas and the §9.1 consistency and subject rules:
   each chain event must pass every rule, and each invalid draft must break exactly the one rule
   it names, with the reason and path it expects;
4. recomputes the `DecisionMade` numbers from the model output and weights (mandate spec §8.3) by
   an independent path, and checks `IntentProposed` against the account chain's `IntentReceived`;
5. seeds bugs, into the validator and into the vectors, and requires every one to be caught.

Usage: `generate.py` (or `generate.py --write`) rewrites the agent-stream section of journal.yaml;
`generate.py --check` fails if the file differs from what this script generates.
"""

import argparse
import calendar
import copy
import hashlib
import itertools
import re
import sys
from dataclasses import dataclass
from datetime import datetime
from decimal import ROUND_DOWN, ROUND_HALF_EVEN, Decimal, InvalidOperation, localcontext
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
VECTORS = ROOT / "docs/specs/reference-cases/journal.yaml"
MARKER = "# ==== agent_stream: generated by reference/journal/generate.py (DEC-177); do not edit by hand ===="

# --------------------------------------------------------------------------- spec §4: canonical form

KEY = re.compile(r"^[a-z][a-z0-9_]{0,63}$")
SHORT_ESCAPES = {'"': '\\"', "\\": "\\\\", "\b": "\\b", "\f": "\\f", "\n": "\\n", "\r": "\\r", "\t": "\\t"}
MAX_INT = 2**53 - 1


def canon_str(text: str) -> str:
    out = []
    for ch in text:
        code = ord(ch)
        if ch in SHORT_ESCAPES:
            out.append(SHORT_ESCAPES[ch])
        elif code < 0x20:
            out.append(f"\\u{code:04x}")
        elif 0xD800 <= code <= 0xDFFF:
            raise ValueError("lone surrogate (spec §4.3)")
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'


def canon(value) -> str:
    """The canonical JSON text of a value tree (spec §4); bytes are its UTF-8 encoding."""
    match value:
        case None:
            return "null"
        case bool():
            return "true" if value else "false"
        case int():
            if not 0 <= value <= MAX_INT:
                raise ValueError(f"integer out of range: {value}")
            return str(value)
        case float():
            raise ValueError("floating-point numbers are rejected (spec §4.5)")
        case str():
            return canon_str(value)
        case list():
            return "[" + ",".join(canon(item) for item in value) + "]"
        case dict():
            for key in value:
                if not KEY.match(key):
                    raise ValueError(f"key outside the spec §4.1 charset: {key!r}")
            return "{" + ",".join(f"{canon_str(k)}:{canon(value[k])}" for k in sorted(value)) + "}"
    raise TypeError(f"not a JSON value: {value!r}")


def canon_bytes(value) -> bytes:
    return canon(value).encode("utf-8")


def sha256_hex(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


DECIMAL_INPUT = re.compile(r"^-?(\d+\.?\d*|\.\d+)([eE][+-]?\d+)?$")
DECIMAL_CANONICAL = re.compile(r"^-?(0|[1-9][0-9]*)(\.[0-9]*[1-9])?$")
DECIMAL_BOUND = Decimal("7.9e28")


def normalize_decimal(text: str) -> str | None:
    """The canonical form of a decimal input, or None if spec §4.6 rejects it."""
    if not DECIMAL_INPUT.match(text):
        return None
    try:
        number = Decimal(text)
    except InvalidOperation:
        return None
    if abs(number) >= DECIMAL_BOUND:
        return None
    plain = format(number, "f")
    if "." in plain:
        plain = plain.rstrip("0").rstrip(".")
    if plain in ("-0", ""):
        plain = "0"
    fraction = plain.partition(".")[2]
    if len(fraction) > 28:
        return None
    return plain


TIMESTAMP = re.compile(r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{9}Z$")


def is_timestamp(text: str) -> bool:
    if not TIMESTAMP.match(text):
        return False
    try:
        instant = datetime.strptime(text[:19], "%Y-%m-%dT%H:%M:%S")
    except ValueError:
        return False
    return 1970 <= instant.year <= 9999


def parse_instant(text: str) -> tuple[datetime, int]:
    return datetime.strptime(text[:19], "%Y-%m-%dT%H:%M:%S"), int(text[20:29])


def epoch_seconds(text: str) -> int:
    """The runtime's risk-clock form of an instant, which the invalid drafts show being refused."""
    return calendar.timegm(parse_instant(text)[0].timetuple())


IDENT = re.compile(r"^[A-Za-z0-9_-]+$")
ULID_ALPHABET = set("0123456789ABCDEFGHJKMNPQRSTVWXYZ")
DIGEST = re.compile(r"^sha256:[0-9a-f]{64}$")


def is_ulid(text: str) -> bool:
    return len(text) == 26 and set(text) <= ULID_ALPHABET and text[0] <= "7"


# --------------------------------------------------------------------------- self-test on version 3


def self_test(v3: dict) -> None:
    """The canonicalizer reproduces every version-3 vector before anything it produces is trusted."""
    for entry in v3["chain"]:
        text = canon(entry["body"])
        assert text == entry["canonical"], f"v3 seq {entry['seq']}: canonical differs"
        assert sha256_hex(text.encode()) == entry["hash"], f"v3 seq {entry['seq']}: hash differs"
    first = v3["chain"][0]
    assert canon({"body": first["body"], "hash": first["hash"]}) == v3["export_line_seq_1"]
    escaping = v3["string_escaping"]
    data = canon_bytes(escaping["object"])
    assert data.hex() == escaping["canonical_utf8_hex"], "v3 string escaping differs"
    assert sha256_hex(data) == escaping["hash"]
    for case in v3["decimal_normalization"]["accept"]:
        assert normalize_decimal(str(case["input"])) == case["canonical"], case
    for rejected in v3["decimal_normalization"]["reject"]:
        assert normalize_decimal(str(rejected)) is None, rejected


# --------------------------------------------------------------------------- closed schemas (§9.1)


@dataclass(frozen=True)
class T:
    """One field type, mirroring the journal's payload type system."""

    kind: str
    inner: T | None = None
    options: tuple[str, ...] = ()
    fields: tuple[tuple[str, T], ...] = ()


STR, ID, ULID, DEC, INT, BOOL, TS, REF = (
    T(k) for k in ("str", "id", "ulid", "dec", "int", "bool", "ts", "ref")
)


def one_of(*options: str) -> T:
    return T("one_of", options=options)


def opt(inner: T) -> T:
    return T("nullable", inner=inner)


def list_of(inner: T) -> T:
    return T("list", inner=inner)


def rec(*fields: tuple[str, T]) -> T:
    return T("record", fields=fields)


MODES = ("normal", "exits_only", "paused", "stopped")
MODE = one_of(*MODES)
MODE_REASONS = one_of(
    "restriction_changed",
    "awaiting_reconciliation",
    "owner_pause",
    "owner_resume",
    "owner_stop",
    "kill_switch",
)
SIDE = one_of("buy", "sell")
ORDER_TYPE = one_of("limit", "market")
TIF = one_of("day", "gtc", "ioc")
RISK_ADDING = ("open", "increase")
DECISION_PURPOSE = one_of("open", "increase", "discretionary_exit", "risk_exit")
INTENT_PURPOSE = one_of("open", "increase", "discretionary_exit", "risk_exit", "owner_exit")
CLIPS = (
    "max_order_usd",
    "position_cap",
    "gross_exposure_cap",
    "target_qty",
    "max_spend_usd",
    "max_avg_price",
)
IGNORED = one_of(
    "not_pinned",
    "model_withdrawn",
    "output_limits",
    "not_in_universe",
    "direction_not_allowed",
    "horizon_mismatch",
    "revision_without_predecessor",
)
STEP_UP = rec(("assertion_id", STR), ("authenticated_at", TS), ("method", STR))

SCHEMAS: dict[tuple[str, str], T] = {
    ("agent", "StreamOpened"): rec(("stream_type", one_of("agent")), ("workspace_id", ID), ("agent_id", ID)),
    ("agent", "ObservationRecorded"): rec(
        ("source", STR), ("instrument_id", opt(STR)), ("as_of", TS), ("data_ref", REF)
    ),
    ("agent", "ModelOutputRecorded"): rec(
        ("model_id", STR),
        ("model_version", STR),
        ("content_hash", REF),
        ("instrument_id", STR),
        ("as_of", TS),
        ("expires_at", TS),
        ("direction", STR),
        ("conviction", DEC),
        ("confidence", DEC),
        ("horizon_s", INT),
        ("thesis_ref", opt(REF)),
        ("evidence", list_of(ULID)),
        ("invalidation", opt(STR)),
        ("thesis_id", opt(ID)),
        ("lineage_id", opt(ID)),
        ("ignored", opt(IGNORED)),
    ),
    ("agent", "DecisionMade"): rec(
        ("instrument_id", STR),
        ("side", SIDE),
        ("type", ORDER_TYPE),
        ("tif", TIF),
        ("qty", DEC),
        ("limit_price", opt(DEC)),
        ("purpose", DECISION_PURPOSE),
        ("exit_conviction", opt(DEC)),
        ("buy_conviction", opt(DEC)),
        ("combined_score", opt(DEC)),
        ("outputs_used", list_of(ULID)),
        ("model_weights", list_of(rec(("key", STR), ("value", DEC)))),
        ("clips_applied", list_of(one_of(*CLIPS))),
        ("dry_run", one_of("allow", "deny", "defer")),
        ("reason_code", opt(ID)),
        ("autonomy", opt(one_of("auto", "ask", "deny"))),
    ),
    ("agent", "IntentProposed"): rec(
        ("instrument_id", STR),
        ("side", SIDE),
        ("type", ORDER_TYPE),
        ("tif", TIF),
        ("qty", DEC),
        ("limit_price", opt(DEC)),
        ("purpose", INTENT_PURPOSE),
    ),
    ("agent", "AgentModeChanged"): rec(
        ("from", MODE), ("to", MODE), ("reason", MODE_REASONS), ("lifecycle", MODE)
    ),
    ("agent", "KillSwitchActivated"): rec(
        ("scope", one_of("agent", "connection", "workspace")),
        ("subject", ID),
        ("initiator", one_of("owner", "risk_limit", "platform_operator")),
        ("mode_event", opt(ULID)),
    ),
    ("agent", "OwnerExitRequested"): rec(
        ("scope", one_of("instrument", "agent", "connection", "workspace")),
        ("subject", ID),
        ("confirmed", BOOL),
        ("bid", opt(DEC)),
        ("bid_size", opt(DEC)),
        ("floor", opt(DEC)),
        ("user", opt(STR)),
        ("step_up", opt(STEP_UP)),
    ),
}

REQUIRED_REFS = {
    "StreamOpened": (),
    "ObservationRecorded": (),
    "ModelOutputRecorded": ("mandate_version",),
    "DecisionMade": ("mandate_version",),
    "IntentProposed": ("mandate_version",),
    "AgentModeChanged": (),
    "KillSwitchActivated": (),
    "OwnerExitRequested": ("mandate_version",),
}
CONFIG_REF_KINDS = (
    "fee_config",
    "trading_calendar",
    "settlement_calendar",
    "instrument_snapshot",
    "rule_set",
    "mandate_version",
    "model_version",
)
ENVELOPE = rec(
    ("envelope_version", INT),
    ("environment", one_of("paper", "live", "backtest")),
    ("event_id", ULID),
    ("stream_id", STR),
    ("event_type", STR),
    ("schema_version", INT),
    ("event_time", TS),
    ("clock_source", one_of("broker", "exchange", "local", "scheduler")),
    ("causation_id", opt(ULID)),
    ("correlation_id", opt(ULID)),
    (
        "actor",
        rec(
            ("kind", one_of("system", "agent", "user", "broker", "platform_operator")),
            ("id", STR),
            ("version", STR),
            ("build", opt(REF)),
        ),
    ),
    ("config_refs", T("object")),
    ("payload", T("object")),
    ("artifact_refs", list_of(REF)),
    ("pii_refs", list_of(STR)),
)
JOURNAL_FIELDS = ("seq", "prev_hash", "recorded_at")


@dataclass(frozen=True)
class Violation:
    rule: str
    reason: str
    path: str


def type_violations(ty: T, value, path: str, skip: frozenset[str]) -> list[Violation]:
    """Every type violation, in the order the journal reports them: extra members first (in key
    order), then the declared members in declaration order."""

    def bad(reason: str, rule: str = "types") -> list[Violation]:
        return [Violation(rule, reason, path)]

    kind = ty.kind
    if kind == "nullable":
        return [] if value is None else type_violations(ty.inner, value, path, skip)
    if kind == "record":
        if not isinstance(value, dict):
            return bad("schema")
        names = [name for name, _ in ty.fields]
        out = []
        if "record.extra" not in skip:
            out += [
                Violation("record.extra", "schema", f"{path}.{k}".lstrip("."))
                for k in sorted(value)
                if k not in names
            ]
        for name, inner in ty.fields:
            member = f"{path}.{name}".lstrip(".")
            if name not in value:
                out.append(Violation("record.missing", "schema", member))
            else:
                out += type_violations(inner, value[name], member, skip)
        return out
    if kind == "list":
        if not isinstance(value, list):
            return bad("schema")
        return [
            v for i, item in enumerate(value) for v in type_violations(ty.inner, item, f"{path}[{i}]", skip)
        ]
    if kind == "object":
        return [] if isinstance(value, dict) else bad("schema")
    if kind == "int":
        ok = isinstance(value, int) and not isinstance(value, bool) and 0 <= value <= MAX_INT
        return [] if ok else bad("schema")
    if kind == "bool":
        return [] if isinstance(value, bool) else bad("schema")
    if not isinstance(value, str):
        return bad("schema")
    checks = {
        "str": lambda s: s != "" or "types.str_nonempty" in skip,
        "id": lambda s: bool(IDENT.match(s)),
        "ulid": is_ulid,
        "dec": lambda s: normalize_decimal(s) is not None,
        "ts": lambda s: is_timestamp(s) or "types.timestamp" in skip,
        "ref": lambda s: bool(DIGEST.match(s)),
        "one_of": lambda s: s in ty.options,
    }
    return [] if checks[kind](value) else bad("non_canonical")


def digest_strings(value) -> set[str]:
    match value:
        case str() if DIGEST.match(value):
            return {value}
        case list():
            return set().union(*(digest_strings(v) for v in value)) if value else set()
        case dict():
            return set().union(*(digest_strings(v) for v in value.values())) if value else set()
    return set()


def ascending(items: list) -> bool:
    """Strictly ascending, so a repeat is refused as well as a swap."""
    return all(a < b for a, b in itertools.pairwise(items))


def strictness(mode: str) -> int:
    return MODES.index(mode)


def consistency_violations(event_type: str, draft: dict, skip: frozenset[str]) -> list[Violation]:
    """The §9.1 consistency rules, evaluated only on a well-typed payload, each reported once."""
    p = draft["payload"]
    out: list[Violation] = []

    def rule(number: int, holds: bool, reason: str, path: str) -> None:
        name = f"rule.{number}"
        if not holds and name not in skip:
            out.append(Violation(name, reason, path))

    if event_type in ("DecisionMade", "IntentProposed"):
        adds_risk = p["purpose"] in RISK_ADDING
        rule(1, (p["side"] == "buy") == adds_risk, "schema", "payload.side")
        priced = p["limit_price"] is not None
        rule(2, priced == (p["type"] == "limit"), "schema", "payload.limit_price")
        rule(3, p["type"] != "market" or not adds_risk, "schema", "payload.type")
    if event_type == "DecisionMade":
        allow = p["dry_run"] == "allow"
        rule(4, (p["reason_code"] is None) == allow, "schema", "payload.reason_code")
        rule(5, (p["autonomy"] is not None) == allow, "schema", "payload.autonomy")
        rule(6, p["dry_run"] != "defer" or p["purpose"] == "discretionary_exit", "schema", "payload.dry_run")
        rule(7, p["autonomy"] in (None, "auto") or p["purpose"] in RISK_ADDING, "schema", "payload.autonomy")
        risk_exit = p["purpose"] == "risk_exit"
        wrong = [
            m for m in ("exit_conviction", "buy_conviction", "combined_score") if (p[m] is None) != risk_exit
        ]
        rule(8, not wrong, "schema", f"payload.{wrong[0]}" if wrong else "")
        rule(9, ascending(p["outputs_used"]), "non_canonical", "payload.outputs_used")
        keys = [w["key"].encode() for w in p["model_weights"]]
        rule(9, ascending(keys), "non_canonical", "payload.model_weights")
        order = [CLIPS.index(c) for c in p["clips_applied"]]
        rule(9, ascending(order), "non_canonical", "payload.clips_applied")
    if event_type == "IntentProposed":
        rule(10, draft["causation_id"] is not None, "schema", "causation_id")
    if event_type == "AgentModeChanged":
        rule(11, strictness(p["to"]) >= strictness(p["lifecycle"]), "schema", "payload.to")
    if event_type == "OwnerExitRequested":
        members = ("bid", "bid_size", "floor", "user", "step_up")
        wrong = [m for m in members if (p[m] is not None) != p["confirmed"]]
        rule(12, not wrong, "schema", f"payload.{wrong[0]}" if wrong else "")
    if event_type == "ModelOutputRecorded" and (p["thesis_id"] is None) != (p["lineage_id"] is None):
        rule(13, False, "schema", "payload.thesis_id" if p["thesis_id"] is None else "payload.lineage_id")
    return out


def subject_violations(event_type: str, draft: dict, skip: frozenset[str]) -> list[Violation]:
    """Rules 14 and 15: a payload that names a subject names this stream's (reason `stream_mismatch`)."""
    _, workspace, agent = draft["stream_id"].split(":")
    p = draft["payload"]
    out = []
    opened = f"agent:{p.get('workspace_id')}:{p.get('agent_id')}"
    if event_type == "StreamOpened" and "rule.14" not in skip and opened != draft["stream_id"]:
        out.append(Violation("rule.14", "stream_mismatch", "stream_id"))
    if event_type in ("KillSwitchActivated", "OwnerExitRequested"):
        expected = {"agent": agent, "workspace": workspace}.get(p["scope"])
        if expected is not None and p["subject"] != expected and f"rule.15.{p['scope']}" not in skip:
            out.append(Violation(f"rule.15.{p['scope']}", "stream_mismatch", "payload.subject"))
    return out


def violations(draft: dict, skip: frozenset[str] = frozenset()) -> list[Violation]:
    """Every rule an agent-stream draft breaks, in the journal's check order (spec §9.1)."""
    out = type_violations(ENVELOPE, draft, "", skip)
    if out:
        return out
    if draft["envelope_version"] != 1:
        return [Violation("envelope", "schema", "envelope_version")]
    event_type = draft["event_type"]
    stream = draft["stream_id"].split(":")
    if event_type not in REQUIRED_REFS:
        return [Violation("catalogue", "unknown_event_type", "event_type")]
    if len(stream) != 3 or not all(IDENT.match(s) for s in stream):
        return [Violation("stream", "non_canonical", "stream_id")]
    if stream[0] != "agent":
        return [Violation("stream", "wrong_stream", "event_type")]
    if draft["actor"]["kind"] in ("system", "agent") and draft["actor"]["build"] is None:
        out.append(Violation("actor", "schema", "actor.build"))
    refs = draft["config_refs"]
    for kind in sorted(refs):
        if kind not in CONFIG_REF_KINDS:
            out.append(Violation("config_refs", "schema", f"config_refs.{kind}"))
        elif not (isinstance(refs[kind], str) and DIGEST.match(refs[kind])):
            out.append(Violation("config_refs", "non_canonical", f"config_refs.{kind}"))
    if "config_refs.required" not in skip:
        missing = [k for k in REQUIRED_REFS[event_type] if k not in refs]
        out += [
            Violation("config_refs.required", "missing_config_ref", f"config_refs.{k}") for k in missing[:1]
        ]
    if draft["schema_version"] != 1:
        return [*out, Violation("catalogue", "unknown_schema", "payload")]
    payload_types = type_violations(SCHEMAS[("agent", event_type)], draft["payload"], "payload", skip)
    out += payload_types
    if not payload_types:
        out += consistency_violations(event_type, draft, skip)
    if "artifact_refs" not in skip and draft["artifact_refs"] != sorted(digest_strings(draft["payload"])):
        out.append(Violation("artifact_refs", "artifact_refs", "artifact_refs"))
    if not ascending(draft["pii_refs"]):
        out.append(Violation("pii_refs", "pii_refs", "pii_refs"))
    if not payload_types:
        out += subject_violations(event_type, draft, skip)
    return out


# --------------------------------------------------------------------------- the agent stream

WORKSPACE = "ws_01J8Z2"
AGENT = "agent_a"
STREAM = f"agent:{WORKSPACE}:{AGENT}"
INSTRUMENT = "b0b6dd9d-8b9b-48a9-ba46-b9d54906e415"
MANDATE = {"mandate_version": "sha256:" + "5" * 64}
ACTOR = {"kind": "agent", "id": AGENT, "version": "0.1.0", "build": "sha256:" + "c" * 64}
INTENT_ID = "01J8Z3M1P0000000000000000X"
IDS = {
    1: "01J8Z3JYA000000000000000G1",
    2: "01J8Z3M0A000000000000000G2",
    3: "01J8Z3M0R000000000000000G3",
    4: "01J8Z3M1A000000000000000G4",
    5: INTENT_ID,
    6: "01J8ZNB0A000000000000000G6",
    7: "01J8ZNB0M000000000000000G7",
    8: "01J8ZNB0R000000000000000G8",
}

QUOTE_SNAPSHOT = {
    "kind": "quote_snapshot",
    "instrument_id": INSTRUMENT,
    "feed": "iex",
    "as_of": "2026-09-21T13:59:58.000000000Z",
    "bid": "149.98",
    "bid_size": "300",
    "ask": "150",
    "ask_size": "200",
}
MODEL_CONTENT = {
    "kind": "signal_model",
    "model_id": "quant.mean_reversion",
    "model_version": "1.0.0",
    "authorship": "platform",
    "code": "reference fixture: stands for the model code, prompt, and parameter schema (mandate spec §8.1)",
    "parameter_schema": {"lookback_days": "integer"},
}
ARTIFACTS = {"quote_snapshot": QUOTE_SNAPSHOT, "model_content": MODEL_CONTENT}

DERIVATION = {
    "note": (
        "Illustrative mandate and account values the DecisionMade vector is recomputed from "
        "(mandate spec §8.3); not a mandate reference case. quant.momentum is configured but has no "
        "fresh output, so it counts as missing. The ask is the observed quote's (artifact quote_snapshot). "
        "The gate dry run and the autonomy result are inputs. The OwnerExitRequested floor is the "
        "default, bid x (1 - max_exit_offset), for the instrument's >= 50 M USD tier "
        "(trading spec §5.5, §5.6)."
    ),
    "owner_bid": "151",
    "max_exit_offset": "0.03",
    "now": "2026-09-21T14:00:00.000000000Z",
    "models": [
        {"model_id": "quant.mean_reversion", "weight": "0.9", "max_output_age_s": 300},
        {"model_id": "quant.momentum", "weight": "0.1", "max_output_age_s": 300},
    ],
    "equity": "10000",
    "market_value": "0",
    "working_opening_cost": "0",
    "gross_exposure": "0",
    "max_position_usd": "5000",
    "max_position_fraction": "0.2",
    "size_factor": "1",
    "entry_threshold": "0.3",
    "exit_threshold": "0.3",
    "rebalance_band": "0.05",
    "max_order_usd": "1500",
    "max_gross_exposure_usd": "10000",
    "increment": "1",
    "min_order_qty": "1",
    "tif": "day",
    "dry_run": "allow",
    "autonomy": "auto",
}


def default_floor(d: dict) -> str:
    return normalize_decimal(str(Decimal(d["owner_bid"]) * (1 - Decimal(d["max_exit_offset"]))))


def artifact_ref(obj: dict) -> str:
    return "sha256:" + sha256_hex(canon_bytes(obj))


def event(seq: int, event_type: str, at: str, recorded: str, payload: dict, **envelope) -> dict:
    body = {
        "envelope_version": 1,
        "environment": "paper",
        "event_id": IDS[seq],
        "stream_id": STREAM,
        "seq": seq,
        "event_type": event_type,
        "schema_version": 1,
        "event_time": at,
        "recorded_at": recorded,
        "clock_source": envelope.get("clock_source", "scheduler"),
        "causation_id": envelope.get("causation_id"),
        "correlation_id": None,
        "actor": dict(ACTOR),
        "config_refs": dict(MANDATE) if REQUIRED_REFS[event_type] else {},
        "payload": payload,
        "artifact_refs": sorted(digest_strings(payload)),
        "pii_refs": [],
        "prev_hash": None,
    }
    return body


def chain_bodies() -> list[dict]:
    quote_ref = artifact_ref(QUOTE_SNAPSHOT)
    model_ref = artifact_ref(MODEL_CONTENT)
    day = "2026-09-21T"
    decision_action = {
        "instrument_id": INSTRUMENT,
        "side": "buy",
        "type": "limit",
        "tif": "day",
        "qty": "10",
        "limit_price": "150",
        "purpose": "open",
    }
    return [
        event(
            1,
            "StreamOpened",
            f"{day}13:00:00.000000000Z",
            f"{day}13:00:00.000150000Z",
            {"stream_type": "agent", "workspace_id": WORKSPACE, "agent_id": AGENT},
            clock_source="local",
        ),
        event(
            2,
            "ObservationRecorded",
            f"{day}13:59:58.000000000Z",
            f"{day}13:59:58.000200000Z",
            {
                "source": "alpaca.iex.quotes",
                "instrument_id": INSTRUMENT,
                "as_of": f"{day}13:59:58.000000000Z",
                "data_ref": quote_ref,
            },
        ),
        event(
            3,
            "ModelOutputRecorded",
            f"{day}13:59:59.000000000Z",
            f"{day}13:59:59.000200000Z",
            {
                "model_id": "quant.mean_reversion",
                "model_version": "1.0.0",
                "content_hash": model_ref,
                "instrument_id": INSTRUMENT,
                "as_of": f"{day}13:59:58.000000000Z",
                "expires_at": "2026-09-22T13:59:58.000000000Z",
                "direction": "long",
                "conviction": "0.97",
                "confidence": "0.98",
                "horizon_s": 86400,
                "thesis_ref": None,
                "evidence": [IDS[2]],
                "invalidation": None,
                "thesis_id": None,
                "lineage_id": None,
                "ignored": None,
            },
        ),
        event(
            4,
            "DecisionMade",
            f"{day}14:00:00.000000000Z",
            f"{day}14:00:00.000100000Z",
            {
                **decision_action,
                "exit_conviction": "0.85554",
                "buy_conviction": "0.75554",
                "combined_score": "0.882",
                "outputs_used": [IDS[3]],
                "model_weights": [
                    {"key": "quant.mean_reversion", "value": "0.9"},
                    {"key": "quant.momentum", "value": "0.1"},
                ],
                "clips_applied": ["max_order_usd"],
                "dry_run": "allow",
                "reason_code": None,
                "autonomy": "auto",
            },
        ),
        event(
            5,
            "IntentProposed",
            f"{day}14:00:00.000000000Z",
            f"{day}14:00:00.000200000Z",
            dict(decision_action),
            causation_id=IDS[4],
        ),
        event(
            6,
            "AgentModeChanged",
            f"{day}20:30:00.000000000Z",
            f"{day}20:30:00.000100000Z",
            {"from": "normal", "to": "stopped", "reason": "kill_switch", "lifecycle": "normal"},
        ),
        event(
            7,
            "OwnerExitRequested",
            f"{day}20:30:00.000000000Z",
            f"{day}20:30:00.000200000Z",
            {
                "scope": "agent",
                "subject": AGENT,
                "confirmed": True,
                "bid": DERIVATION["owner_bid"],
                "bid_size": "300",
                "floor": default_floor(DERIVATION),
                "user": "user_7f3a",
                "step_up": {
                    "assertion_id": "stepup_9c1e",
                    "authenticated_at": f"{day}20:29:45.000000000Z",
                    "method": "webauthn",
                },
            },
        ),
        event(
            8,
            "KillSwitchActivated",
            f"{day}20:30:00.000000000Z",
            f"{day}20:30:00.000300000Z",
            {"scope": "agent", "subject": AGENT, "initiator": "owner", "mode_event": IDS[6]},
        ),
    ]


def hash_chain(bodies: list[dict], genesis: str) -> list[dict]:
    entries, prev = [], genesis
    for body in bodies:
        body["prev_hash"] = prev
        text = canon(body)
        prev = sha256_hex(text.encode())
        entries.append(
            {
                "seq": body["seq"],
                "event_type": body["event_type"],
                "body": body,
                "canonical": text,
                "hash": prev,
            }
        )
    return entries


def draft_of(body: dict) -> dict:
    return {k: copy.deepcopy(v) for k, v in body.items() if k not in JOURNAL_FIELDS}


def set_path(draft: dict, path: str, value) -> None:
    *parents, last = path.split(".")
    node = draft
    for name in parents:
        node = node[name]
    node[last] = copy.deepcopy(value)


def change(path: str, value) -> dict:
    return {"path": path, "value": value}


def invalid(name, clause, seq, changes, reason, path):
    return {
        "name": name,
        "clause": clause,
        "base_seq": seq,
        "changes": changes,
        "expect": {"outcome": "Invalid", "reason": reason, "path": path},
    }


def invalid_drafts() -> list[dict]:
    """Each draft breaks exactly one rule; together they cover every §9.1 rule and each DEC-174
    item-3 contradiction the rulings settle."""
    quote = copy.deepcopy(QUOTE_SNAPSHOT)
    as_of = epoch_seconds("2026-09-21T13:59:58.000000000Z")
    stepped_up = epoch_seconds("2026-09-21T20:29:45.000000000Z")
    return [
        invalid(
            "reason_code_empty_string_on_allow",
            "§4.2",
            4,
            [change("payload.reason_code", "")],
            "non_canonical",
            "payload.reason_code",
        ),
        invalid(
            "owner_exit_unconfirmed_empty_user",
            "§4.2",
            7,
            [
                change("payload.confirmed", False),
                change("payload.bid", None),
                change("payload.bid_size", None),
                change("payload.floor", None),
                change("payload.user", ""),
                change("payload.step_up", None),
            ],
            "non_canonical",
            "payload.user",
        ),
        invalid(
            "model_output_as_of_in_seconds",
            "§4.7",
            3,
            [change("payload.as_of", str(as_of))],
            "non_canonical",
            "payload.as_of",
        ),
        invalid(
            "observation_as_of_as_integer",
            "§4.4",
            2,
            [change("payload.as_of", as_of)],
            "schema",
            "payload.as_of",
        ),
        invalid(
            "step_up_time_in_seconds",
            "§4.7",
            7,
            [change("payload.step_up.authenticated_at", str(stepped_up))],
            "non_canonical",
            "payload.step_up.authenticated_at",
        ),
        invalid(
            "observation_data_inline",
            "§9.1 artifacts",
            2,
            [change("payload.data_ref", quote), change("artifact_refs", [])],
            "schema",
            "payload.data_ref",
        ),
        invalid(
            "observation_artifact_not_listed",
            "§3 artifact_refs",
            2,
            [change("artifact_refs", [])],
            "artifact_refs",
            "artifact_refs",
        ),
        invalid(
            "intent_proposed_carries_intent_id",
            "§9.1 IntentProposed",
            5,
            [change("payload.intent_id", INTENT_ID)],
            "schema",
            "payload.intent_id",
        ),
        invalid(
            "intent_proposed_protective",
            "§9.1 IntentProposed",
            5,
            [change("payload.purpose", "protective")],
            "non_canonical",
            "payload.purpose",
        ),
        invalid(
            "decision_without_mandate_version",
            "§9 required refs",
            4,
            [change("config_refs", {})],
            "missing_config_ref",
            "config_refs.mandate_version",
        ),
        invalid(
            "intent_sell_labelled_open",
            "§9.1 rule 1",
            5,
            [change("payload.side", "sell")],
            "schema",
            "payload.side",
        ),
        invalid(
            "intent_limit_without_price",
            "§9.1 rule 2",
            5,
            [change("payload.limit_price", None)],
            "schema",
            "payload.limit_price",
        ),
        invalid(
            "decision_market_exit_with_price",
            "§9.1 rule 2",
            4,
            [
                change("payload.side", "sell"),
                change("payload.type", "market"),
                change("payload.purpose", "discretionary_exit"),
            ],
            "schema",
            "payload.limit_price",
        ),
        invalid(
            "intent_market_open",
            "§9.1 rule 3",
            5,
            [change("payload.type", "market"), change("payload.limit_price", None)],
            "schema",
            "payload.type",
        ),
        invalid(
            "decision_allow_with_reason_code",
            "§9.1 rule 4",
            4,
            [change("payload.reason_code", "insufficient_buying_power")],
            "schema",
            "payload.reason_code",
        ),
        invalid(
            "decision_deny_with_autonomy",
            "§9.1 rule 5",
            4,
            [change("payload.dry_run", "deny"), change("payload.reason_code", "insufficient_buying_power")],
            "schema",
            "payload.autonomy",
        ),
        invalid(
            "decision_defer_on_open",
            "§9.1 rule 6",
            4,
            [
                change("payload.dry_run", "defer"),
                change("payload.reason_code", "session_not_allowed"),
                change("payload.autonomy", None),
            ],
            "schema",
            "payload.dry_run",
        ),
        invalid(
            "decision_exit_classified_ask",
            "§9.1 rule 7",
            4,
            [
                change("payload.side", "sell"),
                change("payload.purpose", "discretionary_exit"),
                change("payload.autonomy", "ask"),
            ],
            "schema",
            "payload.autonomy",
        ),
        invalid(
            "decision_risk_exit_with_convictions",
            "§9.1 rule 8",
            4,
            [change("payload.side", "sell"), change("payload.purpose", "risk_exit")],
            "schema",
            "payload.exit_conviction",
        ),
        invalid(
            "decision_outputs_repeated",
            "§9.1 rule 9",
            4,
            [change("payload.outputs_used", [IDS[3], IDS[3]])],
            "non_canonical",
            "payload.outputs_used",
        ),
        invalid(
            "decision_weights_unsorted",
            "§9.1 rule 9",
            4,
            [
                change(
                    "payload.model_weights",
                    [
                        {"key": "quant.momentum", "value": "0.1"},
                        {"key": "quant.mean_reversion", "value": "0.9"},
                    ],
                )
            ],
            "non_canonical",
            "payload.model_weights",
        ),
        invalid(
            "decision_clips_out_of_order",
            "§9.1 rule 9",
            4,
            [change("payload.clips_applied", ["position_cap", "max_order_usd"])],
            "non_canonical",
            "payload.clips_applied",
        ),
        invalid(
            "intent_without_causation",
            "§9.1 rule 10",
            5,
            [change("causation_id", None)],
            "schema",
            "causation_id",
        ),
        invalid(
            "mode_looser_than_lifecycle",
            "§9.1 rule 11",
            6,
            [change("payload.to", "exits_only"), change("payload.lifecycle", "paused")],
            "schema",
            "payload.to",
        ),
        invalid(
            "owner_exit_confirmed_without_floor",
            "§9.1 rule 12",
            7,
            [change("payload.floor", None)],
            "schema",
            "payload.floor",
        ),
        invalid(
            "owner_exit_unconfirmed_with_bid",
            "§9.1 rule 12",
            7,
            [change("payload.confirmed", False)],
            "schema",
            "payload.bid",
        ),
        invalid(
            "model_output_lineage_without_thesis",
            "§9.1 rule 13",
            3,
            [change("payload.lineage_id", "lin_01")],
            "schema",
            "payload.thesis_id",
        ),
        invalid(
            "stream_opened_other_agent",
            "§9.1 rule 14",
            1,
            [change("payload.agent_id", "agent_b")],
            "stream_mismatch",
            "stream_id",
        ),
        invalid(
            "kill_switch_other_agent",
            "§9.1 rule 15",
            8,
            [change("payload.subject", "agent_b")],
            "stream_mismatch",
            "payload.subject",
        ),
        invalid(
            "kill_switch_other_workspace",
            "§9.1 rule 15",
            8,
            [change("payload.scope", "workspace"), change("payload.subject", "ws_01J8Z9")],
            "stream_mismatch",
            "payload.subject",
        ),
        invalid(
            "owner_exit_other_agent",
            "§9.1 rule 15",
            7,
            [change("payload.subject", "agent_b")],
            "stream_mismatch",
            "payload.subject",
        ),
    ]


def apply_changes(chain: list[dict], case: dict) -> dict:
    draft = draft_of(chain[case["base_seq"] - 1]["body"])
    for item in case["changes"]:
        set_path(draft, item["path"], item["value"])
    return draft


# --------------------------------------------------------------------------- independent oracles


def dec(text: str) -> Decimal:
    return Decimal(text)


def round12(value: Decimal) -> str:
    with localcontext() as ctx:
        ctx.prec = 60
        return normalize_decimal(str(value.quantize(Decimal("1e-12"), rounding=ROUND_HALF_EVEN)))


def recompute_decision(chain: list[dict], artifacts: list[dict], d: dict) -> dict:
    """Mandate spec §8.3 from the journaled outputs, the observed quote, and the illustrative inputs,
    computed without the vector's own numbers: the members `DecisionMade` must carry."""
    now = parse_instant(d["now"])[0]
    observation = next(e["body"]["payload"] for e in chain if e["event_type"] == "ObservationRecorded")
    quote = next(a["object"] for a in artifacts if a["ref"] == observation["data_ref"])
    ask = dec(quote["ask"])
    outputs = {e["body"]["payload"]["model_id"]: e for e in chain if e["event_type"] == "ModelOutputRecorded"}
    weights = {m["model_id"]: dec(m["weight"]) for m in d["models"]}
    total = sum(weights.values())
    fresh, missing = {}, Decimal(0)
    for model in d["models"]:
        entry = outputs.get(model["model_id"])
        if entry is None:
            missing += weights[model["model_id"]]
            continue
        p = entry["body"]["payload"]
        as_of, expires = parse_instant(p["as_of"])[0], parse_instant(p["expires_at"])[0]
        if as_of <= now < expires and (now - as_of).total_seconds() <= model["max_output_age_s"]:
            fresh[model["model_id"]] = (entry["body"]["event_id"], p)
        else:
            missing += weights[model["model_id"]]
    f = sum(weights[m] * dec(p["conviction"]) * dec(p["confidence"]) for m, (_, p) in fresh.items())
    score = sum(weights[m] * dec(p["confidence"]) for m, (_, p) in fresh.items())
    exit_c, buy_c = f / total, (f - missing) / total
    assert exit_c > -dec(d["exit_threshold"]), "the vector is an entry, not an exit"
    assert buy_c >= dec(d["entry_threshold"]), "the vector must clear the entry threshold"
    cap = min(dec(d["max_position_usd"]), dec(d["max_position_fraction"]) * dec(d["equity"]))
    target = buy_c * cap * dec(d["size_factor"])
    held = dec(d["market_value"]) + dec(d["working_opening_cost"])
    delta = target - held
    band = dec(d["rebalance_band"]) * cap
    assert delta > 0 and delta >= band, "the vector must not hold"
    bounds = [
        ("max_order_usd", dec(d["max_order_usd"])),
        ("position_cap", cap - held),
        (
            "gross_exposure_cap",
            min(dec(d["max_gross_exposure_usd"]), dec(d["equity"])) - dec(d["gross_exposure"]),
        ),
    ]
    value, clips = delta, []
    for name, bound in bounds:
        if bound < value:
            value, clips = bound, [*clips, name]
    assert value >= band, "the clipped value must not fall below the band"
    step = dec(d["increment"])
    qty = (value / ask / step).to_integral_value(rounding=ROUND_DOWN) * step
    assert qty >= dec(d["min_order_qty"])
    return {
        "instrument_id": next(iter(fresh.values()))[1]["instrument_id"],
        "side": "buy",
        "type": "limit",
        "tif": d["tif"],
        "qty": normalize_decimal(str(qty)),
        "limit_price": normalize_decimal(quote["ask"]),
        "purpose": "open" if held == 0 else "increase",
        "exit_conviction": round12(exit_c),
        "buy_conviction": round12(buy_c),
        "combined_score": round12(score / total),
        "outputs_used": sorted(event_id for event_id, _ in fresh.values()),
        "model_weights": [{"key": k, "value": normalize_decimal(str(weights[k]))} for k in sorted(weights)],
        "clips_applied": clips,
        "dry_run": d["dry_run"],
        "reason_code": None,
        "autonomy": d["autonomy"],
    }


def check_chain(section: dict, v3: dict) -> list[str]:
    """Cross-event facts no single draft check can see. Returns every failure, so seeded bugs can be
    shown to be caught."""
    problems = []
    chain = section["chain"]
    by_type = {e["event_type"]: e["body"] for e in chain}
    prev = v3["genesis_prev_hash"]
    for i, entry in enumerate(chain, start=1):
        body = entry["body"]
        if body["seq"] != i or entry["seq"] != i:
            problems.append(f"seq {i}: gap")
        if body["prev_hash"] != prev:
            problems.append(f"seq {i}: prev_hash does not chain")
        if canon(body) != entry["canonical"]:
            problems.append(f"seq {i}: canonical differs")
        if sha256_hex(entry["canonical"].encode()) != entry["hash"]:
            problems.append(f"seq {i}: hash differs")
        prev = entry["hash"]
        if body["stream_id"] != STREAM or body["event_type"] != entry["event_type"]:
            problems.append(f"seq {i}: stream or type differs")
    stored = {a["ref"]: a for a in section["artifacts"]}
    for a in section["artifacts"]:
        if (
            canon(a["object"]) != a["canonical"]
            or "sha256:" + sha256_hex(a["canonical"].encode()) != a["ref"]
        ):
            problems.append(f"artifact {a['name']}: does not re-hash")
    for entry in chain:
        for ref in entry["body"]["artifact_refs"]:
            if ref not in stored:
                problems.append(f"seq {entry['seq']}: artifact {ref} missing")
    if chain[0]["event_type"] != "StreamOpened":
        problems.append("seq 1 is not StreamOpened")
    decision = by_type["DecisionMade"]
    expected = recompute_decision(chain, section["artifacts"], section["derivation"])
    for member, value in expected.items():
        if decision["payload"][member] != value:
            problems.append(f"DecisionMade.{member}: {decision['payload'][member]!r} != recomputed {value!r}")
    intent = by_type["IntentProposed"]
    if intent["causation_id"] != decision["event_id"]:
        problems.append("IntentProposed.causation_id is not the DecisionMade")
    action = {k: decision["payload"][k] for k in intent["payload"]}
    if intent["payload"] != action:
        problems.append("IntentProposed does not repeat the DecisionMade's action")
    received = next(e["body"] for e in v3["chain"] if e["event_type"] == "IntentReceived")
    copied = {k: v for k, v in received["payload"].items() if k not in ("intent_id", "agent_id")}
    if intent["payload"] != copied:
        problems.append("IntentProposed differs from the IntentReceived vector less intent_id and agent_id")
    if (
        received["payload"]["intent_id"] != intent["event_id"]
        or received["causation_id"] != intent["event_id"]
    ):
        problems.append("IntentReceived does not name the IntentProposed as its intent")
    if received["payload"]["agent_id"] != intent["stream_id"].split(":")[2]:
        problems.append("IntentReceived.agent_id is not the agent stream's agent")
    if not intent["recorded_at"] < received["recorded_at"]:
        problems.append("IntentProposed must be recorded before the account stream copies it")
    mode, switch = by_type["AgentModeChanged"], by_type["KillSwitchActivated"]
    if switch["payload"]["mode_event"] != mode["event_id"] or mode["payload"]["reason"] != "kill_switch":
        problems.append("KillSwitchActivated.mode_event does not name its AgentModeChanged")
    if mode["payload"]["to"] != "stopped":
        problems.append("an owner kill switch's final mode is stopped (trading spec §5.5)")
    owner = by_type["OwnerExitRequested"]["payload"]
    derivation = section["derivation"]
    if owner["bid"] != derivation["owner_bid"] or dec(owner["floor"]) != dec(derivation["owner_bid"]) * (
        1 - dec(derivation["max_exit_offset"])
    ):
        problems.append("OwnerExitRequested.floor is not the default floor of its confirmed bid")
    for case in section["invalid_drafts"]:
        got = violations(apply_changes(chain, case))
        want = case["expect"]
        if len(got) != 1 or (got[0].reason, got[0].path) != (want["reason"], want["path"]):
            problems.append(f"{case['name']}: expected exactly {want['reason']} at {want['path']}, got {got}")
    for entry in chain:
        got = violations(draft_of(entry["body"]))
        if got:
            problems.append(f"seq {entry['seq']}: valid event breaks {got}")
    return problems


VALIDATOR_MUTANTS = (
    "record.extra",
    "types.str_nonempty",
    "types.timestamp",
    "artifact_refs",
    "config_refs.required",
    *(f"rule.{n}" for n in range(1, 15)),
    "rule.15.agent",
    "rule.15.workspace",
)


def vector_mutants(section: dict) -> list[tuple[str, dict]]:
    """Seeded bugs in the vectors; the chain check must reject each one."""

    def mutated(fn) -> dict:
        copy_ = copy.deepcopy(section)
        fn(copy_)
        return copy_

    out = []
    for name, fn in [
        (
            "missing model counted as 0 in buy conviction",
            lambda s: s["chain"][3]["body"]["payload"].update(
                buy_conviction=s["chain"][3]["body"]["payload"]["exit_conviction"]
            ),
        ),
        (
            "combined score from conviction",
            lambda s: s["chain"][3]["body"]["payload"].update(combined_score="0.8536"),
        ),
        (
            "every bound listed as a clip",
            lambda s: s["chain"][3]["body"]["payload"].update(
                clips_applied=["max_order_usd", "position_cap", "gross_exposure_cap"]
            ),
        ),
        ("quantity not truncated", lambda s: s["chain"][3]["body"]["payload"].update(qty="10.07")),
        (
            "weights of fresh models only",
            lambda s: s["chain"][3]["body"]["payload"].update(
                model_weights=[{"key": "quant.mean_reversion", "value": "0.9"}]
            ),
        ),
        ("intent differs from its decision", lambda s: s["chain"][4]["body"]["payload"].update(qty="11")),
        ("intent caused by the model output", lambda s: s["chain"][4]["body"].update(causation_id=IDS[3])),
        ("prev_hash not chained", lambda s: s["chain"][5]["body"].update(prev_hash="0" * 64)),
        ("artifact content changed", lambda s: s["artifacts"][0]["object"].update(ask="150.02")),
        ("floor not the default", lambda s: s["chain"][6]["body"]["payload"].update(floor="146.46")),
        (
            "mode_event names another event",
            lambda s: s["chain"][7]["body"]["payload"].update(mode_event=IDS[7]),
        ),
        (
            "invalid draft expects the wrong reason",
            lambda s: s["invalid_drafts"][0]["expect"].update(reason="schema"),
        ),
    ]:
        out.append((name, mutated(fn)))
    return out


def run_mutants(section: dict, v3: dict) -> list[str]:
    escaped = []
    chain = section["chain"]
    cases = [(draft_of(e["body"]), None) for e in chain]
    cases += [(apply_changes(chain, c), c["expect"]) for c in section["invalid_drafts"]]
    for mutant in VALIDATOR_MUTANTS:
        skip = frozenset([mutant])
        caught = False
        for draft, want in cases:
            got = violations(draft, skip)
            if want is None:
                caught |= bool(got)
            else:
                caught |= len(got) != 1 or (got[0].reason, got[0].path) != (want["reason"], want["path"])
        if not caught:
            escaped.append(f"validator mutant {mutant}")
    for name, mutated in vector_mutants(section):
        if not check_chain(mutated, v3):
            escaped.append(f"vector mutant: {name}")
    return escaped


# --------------------------------------------------------------------------- output


def build_section(v3: dict) -> dict:
    chain = hash_chain(chain_bodies(), v3["genesis_prev_hash"])
    artifacts = [
        {"name": name, "ref": artifact_ref(obj), "object": obj, "canonical": canon(obj)}
        for name, obj in ARTIFACTS.items()
    ]
    return {
        "spec": "docs/specs/journal.md v0.5 §9.1 (DEC-177)",
        "stream_id": STREAM,
        "artifacts": artifacts,
        "chain": chain,
        "derivation": DERIVATION,
        "invalid_drafts": invalid_drafts(),
    }


class Dumper(yaml.SafeDumper):
    pass


def split_file(text: str) -> tuple[str, str | None]:
    head, found, tail = text.partition(MARKER + "\n")
    return (head, tail) if found else (text, None)


def render(v3_text: str, section: dict) -> str:
    head, _ = split_file(v3_text)
    body = yaml.dump(
        {"agent_stream": section},
        Dumper=Dumper,
        sort_keys=False,
        allow_unicode=True,
        width=10**6,
        default_flow_style=False,
    )
    return head.rstrip("\n") + "\n" + MARKER + "\n" + body


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="fail if journal.yaml is not what this generates")
    mode.add_argument("--write", action="store_true", help="rewrite the agent_stream section (the default)")
    parser.add_argument("--vectors", type=Path, default=VECTORS, help="the journal.yaml to read or write")
    args = parser.parse_args(argv)
    vectors: Path = args.vectors

    text = vectors.read_text(encoding="utf-8")
    v3 = yaml.safe_load(split_file(text)[0])
    self_test(v3)
    section = build_section(v3)

    problems = check_chain(section, v3)
    problems += run_mutants(section, v3)
    for problem in problems:
        print(f"FAIL {problem}", file=sys.stderr)
    if problems:
        return 1

    rendered = render(text, section)
    reread = yaml.safe_load(rendered)["agent_stream"]
    if check_chain(reread, v3):
        print("FAIL the rendered YAML does not read back to the same vectors", file=sys.stderr)
        return 1
    if args.check:
        if rendered != text:
            print(f"FAIL {vectors} differs; run reference/journal/generate.py", file=sys.stderr)
            return 1
    else:
        vectors.write_text(rendered, encoding="utf-8")
    print(
        f"ok: v3 vectors reproduced; {len(section['chain'])} agent-stream events, "
        f"{len(section['invalid_drafts'])} invalid drafts, {len(VALIDATOR_MUTANTS)} validator and "
        f"{len(vector_mutants(section))} vector mutants caught"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
